- components/HeaderNavMenuDropdown.vue
I think that we no longer need it since when going to the URL, there appears message: "The user deleted their Medium account" ;)
> Removed link to the Medium blog

- layouts/error.vue
- pages/index.vue
I've noticed that on an _index_ and _error_ pages you can't see a footer, although there is still plenty of room to show it. 
- https://nuxtjs.org
- https://nuxtjs.org/error
Fixed footer appearance on `index` and `error` pages
> Footer appearance

- pages/index.vue
It seems a mistake of 'Open Graph' 😄 
Thank you.
> fix: Fix typo 'Grapg' to 'Graph'

- plugins/init.js
Hi nuxtjs.org authors.
First, thank you for awesome documents.
When I ran this codes as dev mode(`npm run dev`), I coundn't watch the japanese transations. So I fixed the codes.
Since `dev mode` is `SSR`,  `setLocale` is never called.
Please feel free to merge it.
Thx :)
> Fixed displaying translations of each country on dev mode.

- static/nuxt-schema.svg
- static/nuxt-views-schema.svg
This PR includes two changes:
1. Converted [nuxt-schema.svg](https://github.com/patrickdaze/nuxtjs.org/blob/convert-to-svg/static/nuxt-schema.svg). It can be found on this page: https://nuxtjs.org/guide
2. Converted [nuxt-views-schema.svg](https://github.com/patrickdaze/nuxtjs.org/blob/convert-to-svg/static/nuxt-views-schema.svg). It can be found on this page: https://nuxtjs.org/guide/views
This PR does not update the text/content of the schemas. It only tries to replicate the same style and text as the original PNGs. The fonts used are the same as in [_document.scss](https://github.com/nuxt/nuxtjs.org/blob/master/assets/scss/base/_document.scss#L15).
Next Step: Once the PR is pulled-in and deployed, I'll create another PR on the nuxt-docs repo to update image links: [I started that …
> Convert schemas to SVGs

- partials/home/backers.vue
- partials/home/modes.vue
- partials/home/welcome.vue
- partials/home/why.vue
- plugins/init.js
- store/index.js
See first: [/nuxt/nuxtjs.org/issues/178](/nuxt/nuxtjs.org/issues/178)
Use api docs server to rendering homepage contents.
This pull request includes:
- Add homepage data store
- Call docs api servers api, `/homepage/*(lang)`, and store it
- Use store data, `$store.state.homepage`, to display contents
- It is the same format as other documents.
- But, "Rendering modes" files contain `content_title` for reproducing the original display
- Move the homepage contents to [/nuxt/docs] repository [/nuxt/docs/pull/1272]
Before merging it, please merge [/nuxt/docs/pull/1272]
> #178: Use api docs server to rendering homepage contents

- partials/home/backers.vue
- partials/home/welcome.vue
See first: [/nuxt/nuxtjs.org/issues/178](/nuxt/nuxtjs.org/issues/178)
Use language resource at the homepage.
This pull request includes:
- Move hardcoded english resources to referer `$store.state.lang.homepage.backer_partners`
Before merging this pull request, please merge [/nuxt/docs/pull/1272](/nuxt/docs/pull/1272) first.
> #178: Use language resource at homepage

- README.md
Because there is a `yarn.lock` file.
> Fix README start command to use `yarn`

- assets/scss/theme/_promote.scss
- partials/home/welcome.vue
The [Nuxt.js Fundamentals](https://vueschool.io/courses/nuxtjs-fundamentals) course is completely free and developed together with the Nuxt.js team.
Adding this subtle banner offer the ability to easily get started with Nuxt.js by watching a quality video course.
I've added a [screenshot](https://i.imgur.com/gpqpS3p.png) for your convenience.
> Link to free Nuxt.js Fundamentals video course

- pages/api/_slug.vue
- pages/examples/_slug.vue
- pages/faq/_slug.vue
- pages/guide/_slug.vue
Changed `occured ` to `occurred`.
related issue: https://github.com/nuxt/docs/pull/1337
cc: @inouetakuya
> fix(docs): typo

- partials/home/backers.vue
Updated the hapi.js link. Changed `hhttps` to `https`.
> fix(link): typo

- assets/scss/theme/_content.scss
Just a small accessibility fix to add visibility to the anchor icon on `:focus`. 
Before:
After:
> Make anchor icon visible on focus

- static/nuxt-views-schema.svg
Fixed the tense of the verb 'supercharge' in two sentences of nuxt-views-schema.svg.
> Fixed typo: supercharges -> supercharged

- assets/css/themes/light/headings.css
The horizontal lines below headings in the docs are floating in the middle of the text if the headings span multiple lines:
I've changed the `::before` pseudo-element added to each heading level to be `::after` and made it a block element with a border colour matching the background colour it had before. It will now always be below the text
> Fix: heading underlines

- components/partials/Search.vue
- package.json
- yarn.lock
Added mousetrap via yarn (`yarn add mousetrap`). 
Bound `/` to focus on the text field.
Tested in chrome, firefox and safari.
---
How should I go about changing the seach text? I see that they are in a separate repo
https://github.com/nuxt/docs
Shall I send a PR for that? How should translations be handled?
> Using mousetrap to focus on search input field via '/' #233

- components/partials/Header.vue
The `<a>` tags inside of the mobile navigation were incorrectly using the `to` object syntax that only works with `<router-link>` and `<nuxt-link>`. This resulted in these links broken links leading to `[object Object]`:
I turned the tags into `<nuxt-link>`'s and changed what was passed to `params.section` because that was also incorrect.
> Fix links in mobile navigation

- components/partials/home/sponsors.vue
- components/partials/home/why.vue
On mobile (tablet and desktop are fine), when the text is justified, it sometimes leaves big gaps:
We could also center align it, but I feel that a left aligned text is more readable.
As for the text about sponsoring, I suggest having it always left aligned.
PS: I love the redesign with Tailwind 😍
> Make text more readable on mobile + shape-outside for round SVG

- components/partials/home/modes.vue
- components/partials/home/why.vue
In my previous pull request (https://github.com/nuxt/nuxtjs.org/pull/244), I missed a few paragraphs.
> On mobile, align paragraphs to the left

- components/partials/Footer.vue
This pull requests changes `Github` to `GitHub` in footer to match the official spelling and the way it's written in other parts of the website.
> fix: correct github spelling

- components/partials/NewsletterForm.vue
> fix(NewsletterForm): email is no longer reactive in success text after subscribing

- components/partials/Header.vue
There was a conflict between `nuxt-link` and the `click` event that prevented the event to be fired.
I added the `native` modifier to fix that.
I also made sure that the action to open the aside navigation is not triggered if we are changing pages.
Closes #253
> Fix mobile aside navigation

- components/partials/NewsletterForm.vue
- components/partials/home/companies.vue
- components/partials/home/modes.vue
- components/partials/home/sponsors.vue
- components/partials/home/welcome.vue
- components/partials/home/why.vue
This PR is part 3 to 7 of #263. In addition to this PR, I created another PR (nuxt/docs/pull/1666).
Using store instead of hard-coded wordings in why section, mode section, companies section, sponsors section and newsletter section. Then, refactor welcome section.
I'm sorry for much file, but I appreciate for your confirmation when you're available. :)
resolve #263
> Update toppage to enable translation

- assets/css/themes/light/headings.css
#267 
Simply setting headings from `display: inline-block` to `display: table` fixes the issue. I can't test on Safari, but latest Firefox/Chrome/Edge/IE seem OK.
I am new contributor so I am not sure if such styling is used anywhere else.
> Fixes horizontal stacking of headings (h1-3) in body of guide articles

- components/partials/Header.vue
This will add padding to the mobile navigation so the links aren't obscured by the bar in the gesture area on iOS devices
> Add padding to mobile-nav based on safe-area-inset to avoid UI overlap

- components/global/bases/AppModal.vue
When using dark mode it was hard for me to find the exit button, and I had to refresh the page to exit the image. I added a simple css fix that I checked across multiple images in the new docs. 
This PR is a fix for issue [411](https://github.com/nuxt/nuxtjs.org/issues/411)
> Fix Exit Button Visibility In Dark Mode

- content/en/guides/get-started/conclusion.md
- content/en/guides/get-started/installation.md
- content/en/guides/get-started/routing.md
I was reading the Nuxt.js documentation under the "Guides" section, thought there were a few fixes I could help with:
**Installation.md**
- one of the `create-nuxt-app` commands was misspelled.
- changed some wording to have more actionable verbiage
- changed wording so it was editor-agnostic; I think beginners will choose whatever editor they want to choose, so rather, the code  should reflect the inherent idea behind the example.
**Routing.md**
- used Vetur practices on some of the code examples
- `<NuxtLink>` can also be converted to `<nuxt-link>`
**Conclusion.md**
- made sentencing more actionable (i.e. less passive tense)
> Optimize english documentation

- content/en/faq/cached-components.md
- content/fr/faq/cached-components.md
- content/id/faq/cached-components.md
- content/ja/faq/cached-components.md
- content/zh/faq/cached-components.md
Hello, 
I realized the sidebar on the current doc shows an item "Using nginx as a proxy" that links to the "How to cache Vue components?" page. This PR corrects it.
> fix link to cached-components in the aside nav

- content/en/api/configuration-generate.md
per https://github.com/nuxt/nuxt.js/blob/dev/packages/utils/src/timer.js#L24 this is in milliseconds and should be specified here
> specify units of interval

- content/en/api/configuration-render.md
- content/en/guides/configuration-glossary/configuration-render.md
- content/ja/api/configuration-render.md
- content/ko/api/configuration-render.md
The `render` subkey is missing in the docs.
This is a follow-up from nuxt/docs#2095
/cc @debs-obrien
> Add missing 'render' subkey in CSP-docs.

- content/en/blog/nuxt-static-improvements.md
There are no `/tree/dev` branch
> fix: correct link to Nuxt Docs

- content/en/api/configuration-build.md
- content/en/guides/configuration-glossary/configuration-build.md
When using `extractCSS`, we also can pass `extract-css-chunks-webpack-plugin` options. Which is supported in https://github.com/nuxt/nuxt.js/blob/15bc5b06e69e08a2dea325dac18cac0dde6d9ca5/packages/webpack/src/config/base.js#L385
This is helpful as a lot users like me got `Conflicting order` warnings from `extract-css-chunks-webpack-plugin`. See issue https://github.com/nuxt/nuxt.js/issues/4885#issuecomment-533015230
> en: add extra options example for extractCSS

- content/en/blog/going-dark-with-nuxtjs-color-mode.md
sans-seriff changes to sans-serif
> Fix 'seriff' Typo to 'serif' in readme.md

- content/ja/guide/commands.md
I updated `ja/guide/commands`.
Ref: https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/438
resolves https://github.com/vuejs-jp/ja.docs.nuxtjs/issues/434
resolves https://github.com/vuejs-jp/ja.nuxtjs.org/issues/17
> docs(ja): Update guide/commands

- content/en/guides/features/file-system-routing.md
Fixed formatting of the last two sections in the page. The trailingSlash section appears in the alert from scrollBehavior
> Fixed formatting of the trailingSlash section

- content/es/guides/internals-glossary/internals-nuxt.md
- content/es/guides/internals-glossary/internals-renderer.md
- content/es/guides/internals-glossary/nuxt-render-and-get-window.md
- content/es/guides/internals-glossary/nuxt-render-route.md
- content/es/guides/internals-glossary/nuxt-render.md
- content/es/guides/internals-glossary/nuxt.md
📝 Finished the missing translations for the internals glossary:
> translation(es-ES)/internals glossary v.2

- content/es/guides/configuration-glossary/configuration-builddir.md
- content/es/guides/configuration-glossary/configuration-cli.md
- content/es/guides/configuration-glossary/configuration-components.md
- content/es/guides/configuration-glossary/configuration-css.md
- content/es/guides/configuration-glossary/configuration-transition.md
Added more Spanish translations for (#543):
📝 guides -> configuration glossary
> translated(es-ES)/configuration glossary

- content/es/guides/configuration-glossary/configuration-env.md
- content/es/guides/configuration-glossary/configuration-extend-plugins.md
- content/es/guides/configuration-glossary/configuration-global-name.md
- content/es/guides/configuration-glossary/configuration-head.md
Pages translated to Spanish for #543 
📝 guides -> configuration-glossary
configuration-env.md
configuration-extend-plugins.md
configuration-global-name.md
configuration-head.md
> [SPANISH] translate guides configuration glossary

- components/global/bases/AppModal.vue
- components/global/bases/BaseAlert.vue
Styles in ```AppModal.vue``` and ```BaseAlert.vue``` are added globally. I think there is no reason they have to be added globally because **the classes in those files are not used in other components at all.**
Thanks.
> Fix Nuxtjs.org page broken layout

- content/en/guide/plugins.md
just noticed a small syntax error in the `https://nuxtjs.org/guide/plugins/` docs
```
asyncData ({ $hello ) {
$hello('asyncData')
}
```
i just added a extra `}` to
```
asyncData ({ $hello }) {
$hello('asyncData')
}
```
> fix small syntax error in plugin docs

- content/en/guides/configuration-glossary/configuration-rootdir.md
- content/en/guides/configuration-glossary/configuration-srcdir.md
- content/es/guides/configuration-glossary/configuration-rootdir.md
- content/es/guides/configuration-glossary/configuration-runtime-config.md
- content/es/guides/configuration-glossary/configuration-srcdir.md
Add the Spanish translation of the following pages.
📝 guides -> configuration glossary
> Translate guides configuration glossary pages to Spanish (es-ES)

- content/en/faq/appengine-deployment.md
- content/en/faq/bip-deployment.md
- content/en/faq/deployment-cloud-run.md
- content/en/faq/deployment-pm2.md
- content/en/faq/dokku-deployment.md
- content/en/faq/github-pages.md
- content/en/faq/heroku-deployment.md
- content/en/faq/netlify-deployment.md
- content/en/faq/nginx-proxy.md
- content/en/faq/now-deployment.md
- content/en/faq/surge-deployment.md
Added a short tutorial on how to deploy to [Bip](https://bip.sh). Bip contains automatic framework detection for NuxtJS, so this is reflected in the guide. 
An example NuxtJS project hosted on Bip is available at https://nuxtjsexample.bip.sh, which utilises [create-nuxt-app](https://github.com/nuxt/create-nuxt-app).
> docs: Add deploy to Bip tutorial

- components/partials/home/HomeWelcome.vue
this happens because the vimeo.com domain is blocked in Indonesia #468
> fix: video not showing for Indonesia

- content/fr/guides/get-started/installation.md
Fix french translation (typos, grammar and some rewrites) for guides/get-started/installation page.
> docs(fr): fix guides/get-started/installation

- content/fr/guides/get-started/routing.md
Fix french translation (typos, grammar and some rewrites) for guides/get-started/routing page.
I will continue to fix translations and might begin to translate missing pages, do you want me to have a complete directory to PR instead of each page ?
> docs(fr): fix guides/get-started/routing

- content/en/api/configuration-render.md
- content/en/guides/configuration-glossary/configuration-render.md
The CSP documentation lacks some crucial information and has a confusing structure. These commits supposed to make that part of the docs more useful.
> Update CSP Documentation

- content/en/guides/configuration-glossary/configuration-ssr.md
Felt that it would be a nice idea to include a link to the deprecated "mode" property here so people understand the connection between the two attributes.
> docs: add hint to mode doc in ssr property

- content/fr/guides/get-started/conclusion.md
- content/fr/guides/get-started/directory-structure.md
- content/fr/guides/get-started/upgrading.md
Fix french translation (typos, grammar and some rewrites) for guides/get-started pages:
- guides/get-started/directory-structure
- guides/get-started/conclusion
- guides/get-started/upgrading
> docs(fr): fix guides/get-started translations

- content/en/guides/features/data-fetching.md
Fixes #723.
Removed the empty line at line 71 to fix the issue. I also noticed a minor typo at line 90 (it was `imlpicitly` instead of `implicitly`) so I fixed that as well. 
The rest are automatically linted by markdownlint.
EDIT: I just remembered line 201 - 203, the template code is auto formatted to a single line. I checked that my VS Code doesn't have auto format on save and it seemed like the autoformatting is only triggered when I commit the changes. Is this normal?
> fix: list bullet & minor typo

- content/en/guides/configuration-glossary/configuration-ssr.md
In the documentation the Configuration glossary has two "mode" properties. The second, further down in the list, was actually SSR. It was alphabetically placed where SSR should be.
This change simply changes the menu item. 
Background: I couldn't find the documentation on the SSR property of the nuxt.config file. Discovered it by accident by going to Mode and seeing a link to SSR, which linked to the second "mode" entry.
> Changed menu item of SSR config item

- assets/css/tailwind.css
- components/TheCookieBox.vue
- components/global/bases/AppModal.vue
- components/partials/ads/CarbonAds.vue
- tailwind.config.js
I noticed there are css definitions for `.container` class and various breakpoints in the `assets/css/tailwind.css` file, as seen here:
https://github.com/nuxt/nuxtjs.org/blob/39c564e9b162efcc42300c1b9c56ec6aa308d7de/assets/css/tailwind.css#L34-L66
However Tailwind CSS already comes with `.container` utility class that has these exact same css definitions with the same breakpoints, as seen in the Tailwind CSS docs over here: https://tailwindcss.com/docs/container
Just to be sure, I've also checked the CDN file for Tailwind CSS and here is a screenshot of the resulting `.container` utility class and breakpoints in it:
Which confirms that it is the exact same, except for the `320px` breakpoint, but the `320px` breakpoint is commented out already so this begs the question why we are …
> refactor: tailwind config & CarbonAds.vue css

- pages/404.vue
While browsing the nuxtjs.org, I noticed that the 404 page was mistake ( LostImageIllustration's position).
> fix:  svg of 404 page is responsive now

- content/id/guides/features/configuration.md
- content/id/guides/features/data-fetching.md
Helping docs translation based on this issue #549 
https://github.com/nuxt/nuxtjs.org/issues/549#issuecomment-683523944
:memo: guides -> features
> [docs-id] Translate guides/features

- components/common/AppLangSelect.vue
Fixes #753 
The issue mentions the language switcher options text color are not visible in dark mode, as seen in this screenshot: ![](https://user-images.githubusercontent.com/9987732/93862787-e390e400-fcc2-11ea-9e90-8dbdf8058435.png)
This doesn't happen for Windows since the option background color is lighter than Mac OS' one, though it's still not super legible:
I suspected it's due to the color being too similar, thus making it seem like it's invisible.  That's because it's very unlikely a code or CSS style will make it literally hidden or disappear in this scenario.
Once I tweaked and overblown the levels of the screenshot from the issue, we can confirm this is the actual cause of it since the text are more visible after the tweak:
It's because the text color is inherited from the …
> fix: options text color for language switcher in dark mode

- content/es/guides/components-glossary/pages-watchquery.md
- content/es/guides/configuration-glossary/configuration-mode.md
- content/es/guides/configuration-glossary/configuration-ssr.md
Related to #543 
Translates the following pages:
* /guides/configuration-glossary/configuration-mode
* /guides/configuration-glossary/configuration-ssr
* /guides/components-glossary/pages-watchquery
> Translate glossary pages

- content/en/guides/directory-structure/layouts.md
Fixes the example code for the default layout which had more than one root element causing a compile error.
> Fix: Add root container to default layout example

- content/es/guides/directory-structure/nuxt-config.md
Translate the following pages to Spanish (es-ES) #543 :
:memo: guides -> directory structure
> Translate guides/directory-structure/nuxt-config.md page to spanish

- content/es/guides/concepts/static-site-generation.md
This commit put a docs spanish page in the root of the repository. https://github.com/nuxt/nuxtjs.org/commit/ff6194d8b4cc13ccd00858b86cb4911952781d84
I made this PR to fix that, and fix some tabs in the start of the page (I don't know is that is important or not.).
> docs: spanish - move page of the root and fix tabs

- content/en/blog/creating-blog-with-nuxt-content.md
Added a warning for placing images from the assets folder in posts articles. Changed warning location for scoped styles to improve readability.
> Added warning for including images in articles

- pages/sponsor-nuxtjs.vue
As `?ref=nuxt` should be part of all URLs, I'd hardcode it in the `a` tag `href` value instead of adding it to each url manually.
> refactor(sponsors): improve ref handling

- content/en/guide/plugins.md
Fix for "Cannot use import statement outside a module" error by adding plugins to the transpile build step.
Source: https://stackoverflow.com/a/61196076
> docs(import error note): Note on fixing import error

- content/en/guides/concepts/context-helpers.md
- content/en/guides/configuration-glossary/configuration-hooks.md
- content/en/guides/configuration-glossary/configuration-router.md
- content/en/guides/directory-structure/nuxt-config.md
- content/en/guides/directory-structure/store.md
- content/en/guides/features/data-fetching.md
- content/en/guides/internals-glossary/internals.md
Fixes spelling mistakes in the English guides.
There were instances of both British English and US English, so I left them as-is. The `nuxt.js` codebase appears to use US English, so I can make the following changes if desired:
- Customising ➡️ Customizing
- artefacts ➡️ artifacts
- behaviour ➡️ behavior
> docs(en): Correct spelling mistakes

- content/en/api/configuration-build.md
- content/en/guides/configuration-glossary/configuration-build.md
- content/es/guides/configuration-glossary/configuration-build.md
- content/fr/api/configuration-build.md
- content/ja/api/configuration-build.md
- content/ja/guides/configuration-glossary/configuration-build.md
- content/pt/guides/configuration-glossary/configuration-build.md
If I understand it correctly, newer versions of `@nuxt/babel-preset-app` does not support the `buildTarget` option anymore.
Anyway, looking at the documentation there is still a reference to that option.
If this is correct, I can expand the PR to other languages as well. If not, feel free to close this PR.
> docs: Replace buildTargets with targets in configuration-build - preset example

- content/en/guides/configuration-glossary/configuration-generate.md
Just a quick PR as it wasn't clear to me if it was seconds or milliseconds.
> docs(en): include the unit for the `interval` property

- content/en/blog/creating-blog-with-nuxt-content.md
The custom injected variable for the article image is "article.img", and is referenced that way throughout the article, but there are two references to "article.image", which does not exist if you follow the tutorial.
> Typo in image references

- content/en/_archives/guide/modules.md
- content/en/guides/directory-structure/modules.md
- content/es/guides/directory-structure/modules.md
- content/fr/guide/modules.md
- content/ja/guide/modules.md
- content/pt/guides/directory-structure/modules.md
This PR updates the Modules guide to refer to **[Hookable](https://github.com/nuxt-contrib/hookable)** instead of **[Hable](https://github.com/jsless/hable)**. It appears that the repository for Hable was transferred to Hookable, as https://github.com/jsless/hable redirects to https://github.com/nuxt-contrib/hookable.
> Update Repository Name in Module Guide

- content/en/guides/directory-structure/plugins.md
- content/es/guides/directory-structure/plugins.md
- content/id/guides/directory-structure/plugins.md
- content/pt/guides/directory-structure/plugins.md
Global Mixins example code had an additional underscore which could lead to confusion over the example for beginner devs; or those who copy + paste this example.
> docs(en/es/id/pt): Updating example code typo in plugins.md

- content/en/guides/configuration-glossary/configuration-render.md
Amends https://github.com/nuxt/nuxtjs.org/pull/989 to add expected release version for https://github.com/nuxt/nuxt.js/pull/8347
> docs(en): add nuxt version tag for `asyncScripts`

- content/en/guides/components-glossary/pages-middleware.md
https://nuxtjs.org/docs/2.x/components-glossary/pages-middleware/
the code snippets show the filename as: `middleware/authenticated.js}` and `pages/secret.vue}`
> fix: curly brackets after filename in docs

- content/en/guides/concepts/static-site-generation.md
Hi. Just removed "and send it" from the static site generation docs to fix the sentence structure.
> fix: remove 'and send it' to fix sentence structure

- content/en/guides/internals-glossary/internals.md
- content/es/guides/internals-glossary/internals.md
- content/fr/guides/internals-glossary/internals.md
- content/id/guides/internals-glossary/internals.md
- content/ja/guides/internals-glossary/internals.md
- content/pt/guides/internals-glossary/internals.md
The `Nuxt Class` link in the 'Core > Nuxt' section of the 'Nuxt Modules Intro' page was incorrectly pointing to the [Using Nuxt.js Programmatically](https://nuxtjs.org/docs/2.x/internals-glossary/nuxt) page.
This change updates the link target from `/docs/2.x/internals-glossary/nuxt` to `/docs/2.x/internals-glossary/internals-nuxt`.
> fix(content): nuxt class link

- content/ja/guides/configuration-glossary/configuration-env.md
Changes a few letters in Japanese translation, to reflect meanings a little bit more precisely.
- "neither available nor defined" -> "利用可能でもなければ定義されてもいない"
- "Each of the `env` properties ... is individually mapped to `process.env.xxxx`" -> "`env` プロパティは `process.env.xxxx` へそれぞれ個別にマップされ"
> docs(ja): Minute changes (ja translation) in env property

- content/en/faq/github-pages.md
This PR adds a new "Github Actions" section to the "How to deploy on Github Pages" FAQ page.
> docs(en): add Github Actions to Github Pages

- components/templates/TheCookieBox.vue
- layouts/default.vue
Use utility padding-bottom to allow footer to appear correctly when cookie banner appears.
> fix (#1099): add dynamic spacing for cookie banner

- content/en/examples/lazy-loading-components.md
Hello 👋
This PR fixes a typo that I noticed in the wording for `content/en/examples/lazy-loading-components.md.` You can find justifications for the changes in the bodies of the commits.
> Fix minor typo

- content/en/guides/internals-glossary/internals-module-container.md
As of current implementation of https://github.com/nuxt/nuxt.js/blob/dev/packages/core/src/module.js
The object syntax for `addPlugin(template)` was missing.
> docs(en) Proposed changes `addPlugin` API

- content/zh/guides/get-started/commands.md
- content/zh/guides/get-started/conclusion.md
- content/zh/guides/get-started/directory-structure.md
- content/zh/guides/get-started/installation.md
- content/zh/guides/get-started/routing.md
- content/zh/guides/get-started/upgrading.md
Updated this part: get-started
📝 guides -> get-started
> docs(zh) update translation：content/zh/guides/get-start

- content/fr/guides/features/data-fetching.md
Replace "montages" with "montag**n**es" (which means "mountains" :mountain: ).
> Fix typo in french documentation

- content/fr/guides/get-started/installation.md
There were two exact same installation methods using create-nuxt-app. Last one looking a bit better so I replaced the first one with it.
> docs(fr): Deleted duplicate installation methods

- content/en/guides/directory-structure/static.md
> docs: add warning about static path when `router.base` is set

- content/en/guides/concepts/server-side-rendering.md
- content/es/guides/concepts/server-side-rendering.md
- content/fr/guides/concepts/server-side-rendering.md
- content/id/guides/concepts/server-side-rendering.md
- content/ja/guides/concepts/server-side-rendering.md
- content/ko/guides/concepts/server-side-rendering.md
- content/pt/guides/concepts/server-side-rendering.md
- content/ru/guides/concepts/server-side-rendering.md
remove serverMiddleware from middleware folder in example
> fix: server docs

- content/en/blog/moving-from-nuxtjs-dotenv-to-runtime-config.md
I may be missing something, but a boolean expression with 2 strings doesn't make a lot of sense, does it? My best guess (and @danielroe in the nuxt discord) was that this example wants to provide different urls depending of production-env or not. Then again why mentioning `.env.example` in the first place? 
So basically this PR is not inteded to provide the best solution, but more to start a conversation.
> docs: update runtimeConfig example to show dynamic baseURL

- content/en/guides/concepts/nuxt-lifecycle.md
asyncData uses context
context contains injected plugins, so it has to come after plugins
> fix: asyncData comes after plugins

- content/en/guides/directory-structure/assets.md
Nuxt makes most of the things automatically so I was thinking that people may think that global CSS files are loaded automatically. Which is not true. This makes it clear.
> Added just a small info tab about global CSS files

- content/en/blog/improve-your-developer-experience-with-nuxt-components.md
Correct the misspelling of 'match' which is currently spelt as 'matche'.
> Correct typographical error

- content/en/guides/configuration-glossary/configuration-alias.md
'data': resolve(__dirname, './assets/other/data') should be 'data': resolve(__dirname, './assets/other/data)'
We should swap the position of the single quotation mark and closing parenthesis in the end
> Fix alias typo

- content/id/guides/internals-glossary/$nuxt.md
- content/id/guides/internals-glossary/context.md
- content/id/guides/internals-glossary/internals-module-container.md
- content/id/guides/internals-glossary/internals-nuxt.md
- content/id/guides/internals-glossary/internals-renderer.md
This is part of #549 
Translate `guides/internals-glossary` to Indonesian
> docs(id): translate internals glossary to Indonesian

- content/id/guides/configuration-glossary/configuration-builddir.md
- content/id/guides/configuration-glossary/configuration-dev.md
- content/id/guides/configuration-glossary/configuration-env.md
- content/id/guides/configuration-glossary/configuration-global-name.md
this is part of #549
📝 guides -> configuration glossary
> docs(id): translate configuration glossary to indonesian

- content/en/video-courses/build-a-job-board-with-laravel-graphql-nuxt-and-apollo.md
- content/en/video-courses/building-application-with-vue-&-nuxt.md
- content/en/video-courses/create-a-news-app-with-vuejs-and-nuxt.md
- content/en/video-courses/get-started-with-nuxt.md
- content/en/video-courses/learn-nuxt-with-debbie.md
- content/en/video-courses/learn-nuxtjs-by-building-a-real-world-app.md
- content/en/video-courses/nuxt.js-vuejs-on-steroids.md
- content/en/video-courses/nuxtjs-fundamentals.md
- content/en/video-courses/scaling-vue-with-nuxtjs.md
- content/fr/video-courses/build-a-job-board-with-laravel-graphql-nuxt-and-apollo.md
- content/fr/video-courses/building-application-with-vue-&-nuxt.md
- content/fr/video-courses/create-a-news-app-with-vuejs-and-nuxt.md
- content/fr/video-courses/get-started-with-nuxt.md
- content/fr/video-courses/learn-nuxt-with-debbie.md
- content/fr/video-courses/learn-nuxtjs-by-building-a-real-world-app.md
- content/fr/video-courses/nuxt.js-vuejs-on-steroids.md
- content/fr/video-courses/nuxtjs-fundamentals.md
- content/fr/video-courses/scaling-vue-with-nuxtjs.md
- i18n/fr-FR.js
- pages/video-courses.vue
FR menu had the faq item that didn't exist anymore. Replace it with the "ressources" page
In EN There was a page with many video.  
In FR, the page was only redirection to the nuxtmastering courses website.
I replace the menu item to link to the new page.
Aiming to allow traduction, i replace the json that was use for listing video by a new content section with ` .md` file and consume it in the template.
Add some minor translation to the example catagory.
I wanted to notice that i get some "issues" on my local env.
The exemple menu item was not working when i'm in dev mode.
Only the menu item (when i directly go /examples all seems to work).
I tested it in FR & EN.
This "bug" was only in dev mode (when i generate / start all was working fine)
> Update FR website

- content/en/guides/features/data-fetching.md
This removes ambiguity on how asyncData merges with component data i.e. only a shallow merge is done. Users should not expect a deep merge.
> docs: asyncData merging type

- components/organisms/AdsBlock.vue
Fix the recursive load of the AdsBlock component
Probably caused by a typo because the component that needs to be loaded seems to be AdBlock, without the extra s.
> fix: remove recursive component reference in `<AdsBlock>`

- content/en/guides/directory-structure/components.md
Migration nuxt/component v1 to v2 makes a great feature about nested directories, starting `nuxt@2.15` using `@nuxt/component v2`. [nested directories nuxt component](https://github.com/nuxt/components#nested-components)
at first, I got problem at nuxt production that update nuxt/component to v2. Many component that not called directly.
I think nuxt-newbie will get this problem when learn it for the first time, so i decide to edit documentation about this update.
I edit documentation about nuxt [nested directories component](https://nuxtjs.org/docs/2.x/directory-structure/components#nested-directories) relate to new update @nuxt/component version 2.
> Update documentation about nested directories components

- content/en/blog/creating-blog-with-nuxt-content.md
In the "List all the blog posts" section, it was passing `params.slug` into `$content()`, but that's not applicable to listing pages.
And it was making my code fail as I was following along, which can take time to track down for a newbie.
> Fix error in example code in creating-blog-with-nuxt-content.md

- content/id/guides/configuration-glossary/configuration-runtime-config.md
- content/id/guides/configuration-glossary/configuration-ssr.md
This is a part of #549.
This pull request provides Indonesian translation for 2 files in `guides -> configuration-glossary`. Details provided below.
Provides translation for the following files:
> docs(id): translation for configuration guides (runtime-config -> ssr)

- renovate.json
The default branch of `nuxt.js.org` has changed from `master` to `main`.
Update `baseBranched` in renovation.json.
> chore: update master -> main for renovate

- content/en/guides/directory-structure/store.md
Added extended file structure representation for full store use on complex projects. If someone could confirm whether the "modules" folder is still required for modules to work under nuxt (essential store/shop/cart/actions.js vs store/modules/shop/cart/actions.js), that would be great.
> docs: add example complex store structure

- content/en/guides/deployment/github-pages.md
- content/fr/faq/github-pages.md
- content/ja/faq/github-pages.md
- content/zh/faq/github-pages.md
Caused by https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/utils/dependencies.js#L11
```
const nodeVersion = '>=12.0.0';
if (!semver.satisfies(process.version, nodeVersion)) {
consola__default['default'].warn(`You are using an unsupported version of Node.js (${process.version}). It is recommended to use the latest LTS version (https://nodejs.org/en/about/releases)`);
}
```
> docs: update node version in github-pages workflow

- nuxt.config.js
Because https://github.com/nuxt-community/eslint-module/pull/46 was fixed and had been released in version 3.0.1. Now in nuxtjs.org is using @nuxtjs/eslint-module version 3.0.2 that we can reenable from now.
> fix: reenable @nuxt/eslint-module

- content/en/guides/concepts/context-helpers.md
While reading the [context helpers guide](https://nuxtjs.org/docs/2.x/concepts/context-helpers), it is mentioned that there are three boolean values injected to the global process. However, only one boolean value was mentioned: `process.client`.
I was curious what the other two were, so I viewed the source code and based on `packages/types/app/index.d.ts`, I inferred that the other two were `server` and `static`.
> docs(context-helpers): specify the three boolean values in process

- content/fr/guides/features/data-fetching.md
Old code
```html
<h1>{{ post.title }</h1>
```
New Code
```html
<h1>{{ post.title }}</h1>
```
> docs(fr): Add a missing brace

- content/en/guides/directory-structure/assets.md
Code reference for url-loader and file-loader was outdated and still referenced the already removed file `lib/builder/webpack/base.js` with last commit `c1e0d174319f209bbfa4d34cfd2e17e82f45537` on October 18, 2018.
I've taken the liberty to evaluate `Object.assign(this.loaders.xxx, { name: this.getFileName('xxx')})` since I think that referencing [build.js](https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/config/build.js#L15-L27) would only serve to confuse the reader.
I've also added the `file-loader` code, since the explanation above stated
> For **these two loaders**, the default configuration is:
Not sure if the intent was to show both `url-loader` and `file-loader` or `url-loader` only.
> docs(assets): update code reference

- content/en/guides/configuration-glossary/configuration-srcdir.md
Inconsistent directory names may have been caused by a previous translation (?)
> fix: correct directory name

- content/en/guides/configuration-glossary/configuration-env.md
Adding example of usage Automatic injection of environment variables on the Windows, since Windows require user a bit different syntax, I noticed a lot of people have this problem and are looking for solution, since not every one uses unix based console. So I propose to add example in the Windows users case.
> docs: add example of setting environment variable on windows

- content/en/guides/directory-structure/modules.md
According to official modules website: https://modules.nuxtjs.org/
Number of Nuxt modules and Maintainers are increased and it is not 145+ and 89+ anymore.
> docs: update number of modules and maintainers

- content/en/guides/features/nuxt-components.md
Update `<client-only>` example to use to use `v-slot` directive instead of deprecated `slot` attribute. (See https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax)
Add a `<base-alert>` informing about the deprecated syntax for versions of nuxt < v2.5.0 and vue < v2.6.0.
> Update deprecated slot attribute to v-slot

- assets/css/content.scss
**🐛 The bug**
When navigating on mobile (SM-G973F) I realized the `<table>` part of the docs were overflowing it's content horizontally.
**🛠️ To reproduce**
The issue is reproducible by running the project locally on your computer and navigating to a `/internals-glossary/**` page, where the markdown translates to a `<table>` on `nuxt-content`
**🔨 The fix**
https://user-images.githubusercontent.com/34862686/117589027-a0726c80-b0fd-11eb-9635-315758131092.mp4
> fix: table overflowing on mobile screen

- content/en/guides/directory-structure/pages.md
The new `fetch` hook introduced in 2.12 is not affected by `watchQuery`，but the description cause a confusion. modify it to match this chapter: https://nuxtjs.org/docs/2.x/components-glossary/pages-watchquery
> docs: solve confusing on `watchQuery` description

- content/en/guides/directory-structure/nuxt-config.md
```
export default {
pages: 'views'
}
```
to
```
export default {
dir: {
pages: 'views'
}
}
```
> docs: Fix dir option example

- content/en/guides/deployment/appengine-deployment.md
If new devs use yarn and then use npm run build, the following error will appear when they execute gcloud app deploy:
ERROR: (gcloud.app.deploy) Error Response: [3] The directory [.yarn/cache] has too many files (greater than 1000).
> Update app engine-deployment.md

- content/en/guides/deployment/deploy-on-moovweb.md
- content/fr/guides/deployment/deploy-on-moovweb.md
- content/ja/guides/deployment/deploy-on-moovweb.md
Moovweb rebranded to [Layer0](https://www.layer0.co/post/introducing-layer0) hence a lot of changes. I work there, and I've made the necessary changes to the deployment process.
> Naming update for Moovweb and Moovweb XDN to Layer0

- content/fr/guides/components-glossary/pages-head.md
When checking the docs I found this example in French for the head function.
But I noticed the 'title' parameter was translated in French to 'titre' making the example invalid.
> Title paramater should not be translated

- content/en/guides/get-started/installation.md
According to v2.15.0 release notes [1] the minimum node version is 12.
[1] https://github.com/nuxt/nuxt.js/releases/tag/v2.15.0
> docs: change minimum node version to 12

- content/en/guides/concepts/context-helpers.md
Updates a link for `context.app` to https://nuxtjs.org/docs/2.x/internals-glossary/context#app
> docs: correctly link context.app to documentation in "Context and Helpers"

- content/en/teams/2.community.md
Current: ![grafik](https://user-images.githubusercontent.com/640208/125037986-21fe6080-e095-11eb-91ec-0467ea5bb0cb.png)
Preview: 
----
According to his [GH page](https://github.com/NicoPennec) and website [https://pennec.io/](https://pennec.io/), Nicolas Pennec lives in Rennes and not in Zurich ☺️ 
I've also changed the capitalization to stay in line with the other names.
> fix(preview): various team info

- content/en/guides/deployment/deployment-stormkitio.md
Dear Nuxt team,
The documentation on deploying Nuxt apps to Stormkit does not exist. I therefore, I drafted a deployment-stormkitio.md. As this is not a real feature request and not a major change, I assume this does not require an Issue to be opened.
> Add deployment documentation for Stormktio

- content/fr/guides/configuration-glossary/configuration-css.md
`npm install --save-dev node-sass sass-loader` -> `npm install --save-dev sass sass-loader@10 fibers`
will trigger an error on build. 
source https://fr.nuxtjs.org/docs/2.x/configuration-glossary/configuration-css
> docs: update sass packages example

- content/en/guides/configuration-glossary/configuration-env.md
People browsing the docs about the `env` property should be informed about the officially recommended alternative runtimeOption properties.
> Add information about runtimeOption properties

- content/en/guides/deployment/deployment-azure-portal.md
Hello, this is just a really small commit to the docs. I just wanted to add some clarity to one of the lines in the docs for deploying to Azure. 
It used to say `This one **won't work for Nuxt** though.`
Now it says `The generated file **won't work for Nuxt** though.`
> Added clarity

- content/en/guides/deployment/github-pages.md
Personal access token is not necesary.
https://github.com/marketplace/actions/github-pages-action#:~:text=For%20newbies%20of%20GitHub%20Actions%3A%20Note%20that%20the%20GITHUB_TOKEN%20is%20NOT%20a%20personal%20access%20token.%20A%20GitHub%20Actions%20runner%20automatically%20creates%20a%20GITHUB_TOKEN%20secret%20to%20authenticate%20in%20your%20workflow.%20So%2C%20you%20can%20start%20to%20deploy%20immediately%20without%20any%20configuration.
> docs: personal access token is not required for github pages deployment

- content/en/0.docs/8.deployment/10.github-pages.md
Personal access token is not necesary.
https://github.com/marketplace/actions/github-pages-action#:~:text=For%20newbies%20of%20GitHub%20Actions%3A%20Note%20that%20the%20GITHUB_TOKEN%20is%20NOT%20a%20personal%20access%20token.%20A%20GitHub%20Actions%20runner%20automatically%20creates%20a%20GITHUB_TOKEN%20secret%20to%20authenticate%20in%20your%20workflow.%20So%2C%20you%20can%20start%20to%20deploy%20immediately%20without%20any%20configuration.
> docs: personal token not required for github pages deployment

- content/en/guides/deployment/deployment-stormkitio.md
This PR updates the Stormkit documentation page by giving more details:
1. It specifies the required steps for SPAs and hybrid applications.
2. It indicates the support channel
3. Updates the steps to setup the application
> Update Stormkit documentation

- content/id/guides/configuration-glossary/configuration-css.md
Coming from https://github.com/nuxt/nuxt.js/issues/8771 I discovered another documentation piece that does not explicitly mention to install version 10 of `sass-loader`.
> docs: update sass-loader recommendation to v10 (indonesian)

- content/en/examples/middleware-router.md
- content/es/examples/middleware-router.md
- content/ja/examples/middleware-router.md
- content/zh/examples/middleware-router.md
Just a minor thing I noticed. The example code does not have a `components/Navigation.vue` file, and instead, the `layouts/default.vue` file is what is using the value of the class from the store.
> docs: correct name of component interacting with router-middleware

- content/en/guides/internals-glossary/internals-module-container.md
to avoid errors when people copy & paste this code
> docs: add missing comma to addPlugin code example

- content/en/guides/directory-structure/modules.md
The title of the page 'modules directory' gives the impression its a page about listing existing modules. In fact, it has really important info about creating your own modules.
> rename title 'modules directory' to 'modules'

- content/en/guides/configuration-glossary/configuration-build.md
`\*_Warning_:` -> `**Warning:**`
> fix markdown typo

- content/en/guides/features/data-fetching.md
This PR adds a simple index as a key to the v-for elements. Without a key, the example errors.
> chore(examples): add missing key to v-for for data-fetching

- components/templates/home/Why.vue
- content/en/blog/creating-a-nuxt-module.md
- cypress/integration/home.spec.js
As discussed with @Atinux, this adds an option to choose StackBlitz to run the Nuxt starter in WebContainer.
Small notes:
- I've opted for this text + buttons structure in order to keep the translations intact.
- The additional div wrapper is added to ensure a nice layout of the buttons on viewports <640px
> docs: add StackBlitz online demo link to homepage

- content/en/guides/directory-structure/plugins.md
I was searching forever to see how to use `options` in a plugin. Is this mentioned in the docs somewhere? Couldn't find it.  
Looking at these helped:
- https://stackoverflow.com/questions/57756064/pass-data-from-nuxt-module-to-plugin
- https://github.com/nuxt-community/community-modules/issues/170#issuecomment-346764312
Happy to close this if this is documented somewhere. Happy to modify this as well to make this fit better into the current docs.
> docs: add options usage to example

- static/_redirects
Fix broken rules and add `/docs/2.x/features/*` redirect rules
resolve nuxt/nuxtjs.org#1697
> fix: 2.x features redirects

- content/en/docs/3.features/5.meta-tags-seo.md
This PR attempts to clarify the difference between setting the `head` to an object vs. as a function. It also removes _Resource Hints_ as they belong to the render configuration, not metadata and SEO https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-render#resourcehints
> docs: change example to `head` object and remove resource hints

- content/en/docs/2.concepts/2.context-helpers.md
This PR attempts to fix things that caught my attention while reading this fine article, namely:
- Explains what HMR is. 
- Removes some redundant words. 
- Cross-references the store directory when referencing Vuex.
- Links out to the MDN glossary definition of Falsy.
- Explains what DX/UX is.
It'd be great to have a acronym/definition type component that one could use, e.g. 
```html
<acronym def="Hot Module Reload / Replacement">HMR</acronym>
```
styled e.g. as
```css
display: inline-block;
border-bottom: dashed 1px silver;
cursor: help;
```
> docs: add definitions for acronyms + technical terms

- content/ja/docs/7.components-glossary/1.fetch.md
Currently, the purpose of `fetchDelay` is explained as "過剰実行を防ぐため", which means "to avoid excessive execution".
I think this is not correct.
I propose changing the phrase to "極短期間での画面切り替えによるちらつきを防ぐため", which is google translated as:
"To prevent flicker due to screen switching in a very short period of time"
(Note: the original phrase was: "to avoid quick flashes", which I could not come up with concise phrase, so a bit descriptive)
> docs(ja): update 1.fetch.md

- components/templates/Releases.vue
- i18n/en-US.js
- i18n/fr-FR.js
- i18n/ja-JP.js
Using named formatting is much easier to maintain.
https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting
The message of an i18n resource can understand context-sensitive by using parameters.
From a localization point of view, you can also benefit from named formatting.
> refactor: release on datetime with named formatting

- content/en/integrations/deployments/nginx.md
> docs: typo fix (`as` -> `and`)

- content/en/docs/4.directory-structure/9.pages.md
I stumbled across this option reading the code, I think it would be very worthwhile to document it.
It would also explain why route navigation in Nuxt will destroy/recreate page components even if the same component is used in two routes. I'm not debating the behaviour at all, I agree with it, but as it doesn't match the norm for a Vue project, no harm having something in the documentation which explains it.
> docs: Include Page.key option in documentation

- content/en/docs/4.directory-structure/3.components.md
> However, if we want to keep `Button.vue`, we can use the `prefix` option in the `nuxt.config.js` configuration file to add a prefix to all components in a given directory:
I think this sentence is quite unclear. First, what does it mean by "keep `Button.vue`"? I'm guessing it means "keep using `<Button />`". Second, it mentioned "use the `prefix` option", but it did not provide any `prefix` option in the example below.
> Thus, we can use `BaseButton` in the template instead of `Button` without having to change the name of the `Button.vue` file.
This sentence is quite unclear too. First, why can we "use `BaseButton`"? According to the example code given, we should not be able to use `<BaseButton />`. We can only use `<FooButton />`. Second, why "we can use `BaseButton` instead of …
> docs: Explain component directory better

- content/en/docs/5.configuration-glossary/5.configuration-css.md
- content/fr/docs/5.configuration-glossary/5.configuration-css.md
- content/ja/docs/5.configuration-glossary/5.configuration-css.md
- content/pt/docs/5.configuration-glossary/5.configuration-css.md
Fixes EN content typo (missing `::`)
And updates other languages (sorry about FR diff, actually almost nothing changed)
> fix(content): fix EN doc + update localised doc

- content/ja/docs/1.get-started/2.routing.md
English text
```
If you have used vue-router before, you can think of the <NuxtLink> as a replacement for <RouterLink>
```
> Fix Japanese translation

- components/molecules/EditOnGithub.vue
- nuxt.config.ts
- plugins/modules.js
- plugins/newsletter.js
- plugins/partner.js
Fixes the usage of environnement variables on runtime. Should use `publicRuntimeConfig` instead of `process.env`.
> chore(env): fix env variables usage on runtime

- content/en/_collections/navigations/footer.md
- content/en/_collections/navigations/header.md
- content/en/index.md
- content/es/_collections/navigations/footer.md
- content/es/_collections/navigations/header.md
- content/es/index.md
- content/fr/_collections/navigations/footer.md
- content/fr/_collections/navigations/header.md
- content/fr/index.md
- content/ja/_collections/navigations/footer.md
- content/ja/_collections/navigations/header.md
- content/ja/index.md
- content/pt/_collections/navigations/footer.md
- content/pt/_collections/navigations/header.md
- content/pt/index.md
- static/_redirects
To merge even if https://modules.nuxtjs.org is not redesigned. At least it works well 🙂
> chore: redirect `/modules` to `modules.nuxtjs.org`

- content/en/docs/3.features/6.configuration.md
- content/es/docs/3.features/6.configuration.md
- content/fr/docs/3.features/6.configuration.md
- content/ja/docs/3.features/6.configuration.md
- content/pt/docs/3.features/6.configuration.md
Removed installation instructions from documentation as fibers does not support node16 and above
Also, since the latest version of node is 16 at the moment, I thought that the document based on the version before 16 is inappropriate.
> Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit dacc2fee0f is a breaking change and workarounds are non-trivial.
https://github.com/laverdet/node-fibers
> fix(docs): remove install fibers

- content/ja/docs/6.internals-glossary/9.nuxt.md
There was a very small typo, which has been corrected.
> docs(ja): fix mini typo 6.internals-glossary/9.nuxt.md

- content/en/deployments/github-pages.md
Deployment docs for GitHub pages contains only npm, I simply added code groups with yarn
> Docs: added yarn in github page deployment

- components/organisms/ads/BannerMasteringNuxt.vue
This PR fixes a minor visual bug in the background of the Black Friday banner on landscape tablet viewport.
**Before:**
**After:**
Related to https://github.com/nuxt/nuxtjs.org/pull/1940
> Fix landscape tablet viewport banner background

- components/organisms/ads/BannerMasteringNuxt.vue
fixed banner's background image overflow
> fix: BannerMasteringNuxt image overflow

- content/en/docs/5.configuration-glossary/5.configuration-css.md
As of April 2021 maintainers of `fibers` announced it does not work with the current LTS version of Node (16.x) and "[recommends you avoid its use if possible](https://github.com/laverdet/node-fibers/blob/8f2809869cc92c28c92880c4a38317ae3dbe654d/README.md?plain=1#L1)". The authors README.md commit titled "[the end](https://github.com/laverdet/node-fibers/commit/8f2809869cc92c28c92880c4a38317ae3dbe654d)" along with the verbiage "_inevitable that one day this library will abruptly stop working and no one will be able to do anything about it_" suggest this package will not be maintained going forward.
Other benefits of the change:
- Bring this page into alignment with [The Nuxt Configuration Guide](https://nuxtjs.org/docs/features/configuration/) which does not suggest users install fibers. …
> docs: remove `fibers` dependency recommendation

- content/en/deployments/github-pages.md
- content/en/docs/3.features/6.configuration.md
- content/en/docs/4.directory-structure/2.assets.md
- content/en/docs/4.directory-structure/8.modules.md
- content/en/tutorials/3.going-dark-with-nuxtjs-color-mode.md
- content/es/docs/3.features/6.configuration.md
- content/es/docs/4.directory-structure/2.assets.md
- content/es/docs/4.directory-structure/8.modules.md
- content/es/docs/5.configuration-glossary/5.configuration-css.md
- content/es/tutorials/3.going-dark-with-nuxtjs-color-mode.md
- content/fr/docs/3.features/6.configuration.md
- content/fr/docs/4.directory-structure/2.assets.md
- content/fr/docs/4.directory-structure/8.modules.md
- content/fr/docs/5.configuration-glossary/5.configuration-css.md
- content/fr/tutorials/3.going-dark-with-nuxtjs-color-mode.md
- content/ja/docs/3.features/6.configuration.md
- content/ja/docs/4.directory-structure/2.assets.md
- content/ja/docs/4.directory-structure/8.modules.md
- content/ja/docs/5.configuration-glossary/5.configuration-css.md
- content/ja/tutorials/3.going-dark-with-nuxtjs-color-mode.md
- content/pt/docs/3.features/6.configuration.md
- content/pt/docs/4.directory-structure/2.assets.md
- content/pt/docs/4.directory-structure/8.modules.md
- content/pt/docs/5.configuration-glossary/5.configuration-css.md
- content/pt/tutorials/3.going-dark-with-nuxtjs-color-mode.md
First PR to Nuxt 🙂
Because #1966 and #1921 are not complete, I have definitely deleted the recommendation.
I also harmonized the `yarn add` command.
In several places we had `-D` option and in other places `--dev`. I chose `--dev` because it's understandable to everyone, and fits well with the `--save-dev` of npm.
> docs: remove lingering fibers dependency recommendations

- content/en/examples/9.plugins/1.vue.md
Hi! I'm a first-time contributor, please let me know if there is any specific reading on contributing to Nuxt!
This is a minor docs fix for a couple of types on the Plugins example page.
- Remove a double period
- show -> shows
> docs(en): fix typos on Examples -> Plugins -> Vue Plugins

- content/en/docs/5.configuration-glossary/10.configuration-extend-plugins.md
according to the docs https://nuxtjs.org/docs/configuration-glossary/configuration-plugins#the-plugins-property, plugin array is array of string or objects. We have encountered with an issue with @nuxtjs/composition-api which has not object structure.
> docs: handle additional case when extending plugins

- content/en/tutorials/1.creating-blog-with-nuxt-content.md
Fix incorrect image link for `Author.vue` `NuxtLink` example.
In the first example we create the author like this:
```markdown
---
author:
name: Benjamin
bio: All about Benjamin
image: https://images.unsplash.com/.....
---
```
And yet in the example when we wrap it in `<NuxtLink>` the code wrongly displays `author.img`.
> docs: fix typo

- content/en/docs/3.features/8.nuxt-components.md
I've tried to add `#placeholder` in my placeholder component inside `client-only` but it didn't work.
It worked after changing it into `slot="placeholder"`
> docs: add template wrapper for client-only placeholder

- components/organisms/home/HomeDiscoverPartners.vue
- components/organisms/home/HomeExplore.vue
Hi. I realize Discover Partners section in the home page of nuxtjs.org has z-index issue on certain -especially high- resolutions. 
I just add "z-20" class to section and it is fixed.
Addition: I just realized that the same problem exists in the Explore section. :)
https://user-images.githubusercontent.com/6717356/149040131-5b8606ec-3879-49a5-b36a-7797d6d7b8f5.mov
> fix: z-index issue Discover Partners/Explore section in the home page

- content/en/examples/5.seo/2.twitter-og.md
Updated file name and removed duplicated "the" article
> docs: fix page filename and typo

- content/en/docs/2.concepts/1.views.md
Since we want to show page properties we should open appropriate page
> docs: link to pages

- content/en/docs/3.features/4.data-fetching.md
In the documentation, there was a spacing issue where two sentences ran together without a space after the period.
> Fix spacing

- content/en/docs/5.configuration-glossary/11.configuration-generate.md
Add missing `you` and space between `.` and `If`.
> Fix typo in generate routes() docs

- content/pt/docs/3.features/1.rendering-modes.md
- content/pt/docs/3.features/10.transitions.md
- content/pt/docs/3.features/11.live-preview.md
- content/pt/docs/3.features/2.deployment-targets.md
- content/pt/docs/3.features/3.file-system-routing.md
- content/pt/docs/3.features/4.data-fetching.md
- content/pt/docs/3.features/5.meta-tags-seo.md
- content/pt/docs/3.features/6.configuration.md
- content/pt/docs/3.features/7.loading.md
- content/pt/docs/3.features/8.nuxt-components.md
- content/pt/docs/3.features/9.component-discovery.md
- content/pt/docs/3.features/index.md
In this pull request I am pushing the translated files,
that belong to section features of the documentation.
the specific folder is: `content/pt/docs/3.features`
With exceptions of `case-studies`, `articles`, `announcements`,
I already translated the whole website.
It possible that @ChristopheCVB may have other occupations,
but I would like to ask him if is it possible for him to visit this section of pull requests twice per week?
I believe we can go more quick with the updates.
@smarroufin and @ChristopheCVB it is your turn now 🙂.
> Add the section features of the documentation translated

- content/en/docs/1.get-started/1.installation.md
Changed the first sentence in paragraph 190 
from: 
- When you run the dev command it will create .nuxt folder.
to:
- When you run the dev command it will create a .nuxt folder.
Helps make readers understand we are referring to a particular item (folder) in the sentence.
> ⚡️ modified sentence to improve readers' comprehension 

- content/en/docs/5.configuration-glossary/11.configuration-generate.md
- content/es/docs/5.configuration-glossary/11.configuration-generate.md
- content/fr/docs/5.configuration-glossary/11.configuration-generate.md
- content/ja/docs/5.configuration-glossary/11.configuration-generate.md
- content/pt-br/docs/5.configuration-glossary/11.configuration-generate.md
Fixes broken markdown link in all locales, except PT since it will be fixed in #2044
> chore(content): fix markdown link

- content/en/docs/4.directory-structure/9.pages.md
Remove incorrect use of "this" in SFC templates.
> docs: Remove "this" from VUE SFC template code

- content/en/docs/3.features/7.loading.md
Alert: I have experienced a case where the loading bars did not appear between routes. I wnated beginners, such as myself, to know what is happening.
Missing Coma: A few sentences were hard to understand due to missing coma.
Sentence: A few sentences were hard to understand due to the structure.+
> docs: add alert, add missing coma, change sentence (in docs/features/loading)

- content/en/docs/3.features/3.file-system-routing.md
- content/en/docs/3.features/8.nuxt-components.md
- content/en/docs/5.configuration-glossary/25.configuration-router.md
- content/en/docs/6.internals-glossary/1.context.md
- content/en/examples/1.routing/2.active-link-classes.md
- content/es/docs/3.features/3.file-system-routing.md
- content/es/docs/3.features/8.nuxt-components.md
- content/es/docs/5.configuration-glossary/25.configuration-router.md
- content/es/docs/6.internals-glossary/1.context.md
- content/es/examples/1.routing/2.active-link-classes.md
- content/fr/docs/3.features/3.file-system-routing.md
- content/fr/docs/3.features/8.nuxt-components.md
- content/fr/docs/5.configuration-glossary/25.configuration-router.md
- content/fr/docs/6.internals-glossary/1.context.md
- content/fr/examples/1.routing/2.active-link-classes.md
- content/ja/docs/3.features/3.file-system-routing.md
- content/ja/docs/3.features/8.nuxt-components.md
- content/ja/docs/5.configuration-glossary/25.configuration-router.md
- content/ja/docs/6.internals-glossary/1.context.md
- content/ja/examples/1.routing/2.active-link-classes.md
- content/pt-br/docs/3.features/3.file-system-routing.md
- content/pt-br/docs/3.features/8.nuxt-components.md
- content/pt-br/docs/5.configuration-glossary/25.configuration-router.md
- content/pt-br/docs/6.internals-glossary/1.context.md
- content/pt-br/examples/1.routing/2.active-link-classes.md
- content/pt/docs/3.features/3.file-system-routing.md
- content/pt/docs/3.features/8.nuxt-components.md
- content/pt/docs/5.configuration-glossary/25.configuration-router.md
- content/pt/docs/6.internals-glossary/1.context.md
- content/pt/examples/1.routing/2.active-link-classes.md
vue-router's [/en/](https://router.vuejs.org/en/) leads to a non-existent page. Latest vue-router (4.x) is built for Vue 3, so they should link to 3.x docs.
> docs: fix vue-router link

- i18n/pt-PT.js
- nuxt.config.ts
Enables Portuguese in i18n config, allowing users to browse Portuguese pages.
PT translation is almost complete (>90%) thanks to a massive contribution from @nazarepiedady and reviews from @ChristopheCVB.
Having the language enabled will help translators as well as reviewers for deploy previews.
> chore(i18n): enable portuguese language

- content/es/docs/1.get-started/1.installation.md
- content/fr/docs/1.get-started/1.installation.md
I noticed that the french translation's branch for the stackblitz example was wrong.
> fix: changed branch for stackblitz's link

- content/en/docs/4.directory-structure/12.store.md
current store directory documentation exports const getter instead of getters
I don't think that's intended as it will cause issues accessing it / mapping it through map helpers
> docs: fix typo getter

- content/en/deployments/koyeb.md
According to the whole example, the exposed port of the Docker should be 3000, as the nuxt app starts on port 3000
> docs: Update koyeb.md

- content/en/docs/5.configuration-glossary/15.configuration-ignore.md
PR to help address https://github.com/nuxt/nuxt.js/issues/6459
Some projects may want to have their srcDir different from the default and still be able to .nuxtignore files during development. A one-liner in the docs may help devs put the .nuxtignore file in the correct location.
> docs: Added a line about `srcDir` for .nuxtignore

- content/en/docs/4.directory-structure/12.store.md
current docs provide an example of the store actions having a `state` parameter whereas it's supposed to be `context`
> docs: fix typo actions parameter

- components/theme/app/AsideBottom.vue
This small commit changes Nuxt 3 status on page to remove ambiguity for new users and encourage them to try Nuxt 3
> docs: replace Nuxt 3 `Beta` label with `RC`

- content/pt/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md
In this repository, I am sending the translation for the
`tutorials/moving-from-nuxtjs-dotenv-to-runtime-config.md`.
I intend to translate all tutorials, so this probably will not be
the last update for the Portuguese folder.
I am waiting for your reviews @smarroufin and @ChristopheCVB.
> docs(pt): translate `tutorials/moving-from-nuxtjs-dotenv-to-runtime-config.md`

- content/en/docs/1.get-started/4.commands.md
For coherence on the page, I mentioned putting `dist/` in `.gitignore` as this was not mentioned as it does for putting `.nuxt` in `.gitignore`
Under the following sentence in the docs, it is mentioned to ignore `.nuxt`
> Nuxt will create a .nuxt directory with everything inside ready to be deployed on your server hosting.
> We recommend putting .nuxt in .npmignore or .gitignore.
However under the same sentence for `.dist` the ignore step is not mentioned.
> Nuxt will create a dist/ directory with everything inside ready to be deployed on a static hosting service.
This causes a significant confusion from a learners point of view and incoherence in the docs.
> docs: mention putting `dist/` in `.gitgnore`

- nuxt.config.ts
This PR adds the following script to the nuxtjs.org website:
```
https://masteringnuxt.com/banners/main.js
```
This external script does the following:
- Adds a fixed top `<a>` to the body and renders the banner inside
- Adds a `<style>` tag to properly style it
- Adds the `.has-bb-banner` class to the body, plus a class name derived of the host. In this case, `.nuxtjs_org`
- Adds custom CSS to push down the fixed elements of the page (in this case, the navbar and sidebars) when the `.has-bb-banner` class is present in the body tag. This custom CSS depends on the host name. For nuxtjs.org, it is:
```
body.has-bb-banner.nuxtjs_org .d-header {
top: 72px;
}
body.has-bb-banner.nuxtjs_org .top-header {
top: calc(var(--header-height) + 72px);
}
```
The banner opens Mastering Nuxt's site in a …
> chore: Add Mastering Nuxt top banner script

- nuxt.config.ts
This PR replaces the current "Mastering Nuxt" top banner with the "Join Nuxt Nation" banner.
It opens https://nuxtnation.com in a new tab. If closed it does not open again (key saved in Local Storage).
[More screenshots](https://imgur.com/a/6rA4RJn)
> Replace top banner with Nuxt Nation banner

- content/en/docs/2.concepts/1.views.md
On macOS uppercase is not an issue, but when building with github actions for instance, it is. So better to remove the misleading uppercase altogether.
> docs: lowercase `app.html`

- content/en/examples/2.data-fetching/1.async-data.md
This PR fixes minor typo for asyncData hook readme as per the code sandbox example linked - https://codesandbox.io/s/github/nuxtlabs/examples/tree/master/data-fetching/async-data-hook?from-embed
> docs: fix typo in example description

- content/en/docs/4.directory-structure/12.store.md
fix typo. It should be "getters" instead of "getter"
> docs: fix typo in "getters" file name

- content/en/docs/1.get-started/1.installation.md
Recently `Volar` is recommended by the Vue developers as the must have vs-code extension.
> docs: recommend volar instead of vetur

- content/en/deployments/stormkitio.md
- Hybrid applications are detected automatically so there is no more need to switch the toggle. 
- Suggest using `redirects.json` instead of `stormkit.config.yml`
> docs: update stormkit instructions

- content/en/docs/2.concepts/2.context-helpers.md
- content/en/docs/6.internals-glossary/1.context.md
Related to https://github.com/nuxt/nuxt.js/pull/9332
> feat: add beforeSerialize

- nuxt.config.ts
This PR is similar to https://github.com/nuxt/nuxtjs.org/pull/2159
It adds an external script that renders the top banner of Mastering Nuxt at the top of the site. When clicked, it opens the Mastering Nuxt website in a new tab.
To quickly preview the banner on your website, you can follow these steps:
- Go to nuxtjs.org
- Open the developer toolbar
- Run the following:
```
const script = document.createElement('script');
script.type = 'text/javascript';
script.src = 'https://masteringnuxt.com/banner.js?affiliate=nuxt&type=top';    
document.head.appendChild(script);
```
That will add the script to the head and give you a live preview of how it will look when this PR gets merged.
Here's an screencast of the banner in action: https://imgur.com/a/B89zOiL
Let me know if you have comments or …
> Add new Mastering Nuxt top banner

- content/en/deployments/google-appengine.md
https://cloud.google.com/appengine/docs/standard/nodejs/release-notes since the 11 of April, you need to include `"gcp-build":""` script in your package.json if you building the app locally before deploying to GCP. Google Cloud changed its default behavior on building the repo.
If you don't include the script server returns 404 as it is unable to serve compiled files from your build dir.
> docs: Update google-appengine.md due to recent breaking changes in GCL

- content/en/docs/5.configuration-glossary/2.configuration-build.md
- content/es/docs/5.configuration-glossary/2.configuration-build.md
- content/fr/docs/5.configuration-glossary/2.configuration-build.md
- content/ja/docs/5.configuration-glossary/2.configuration-build.md
- content/pt-br/docs/5.configuration-glossary/2.configuration-build.md
- content/pt/docs/5.configuration-glossary/2.configuration-build.md
Now https://ssr.vuejs.org/en/css.html will redirect to https://vuejs.org/guide/scaling-up/ssr.html, this PR updates the link to https://v2.ssr.vuejs.org/en/css.html.
> docs: update old ssr/css link

- content/fr/examples/1.routing/2.active-link-classes.md
The link currently points to ja locale.
This PR intends to points to the fr version of the documentation instead
> Update fr link 2.active-link-classes.md

- i18n/pt-PT.js
In this pull request, I would like to mark the beginning of update of Portuguese documentation to match the work that I am doing over the [pt.vuejs.org](https://github.com/vuejs-translations/docs-pt) and that will be done over [nuxt-docs-pt](https://github.com/nazarepiedady/nuxt-docs-pt) for Nuxt 3.
Vue 2 and Nuxt 2 are more present than programmers think, so I am counting with your help and support in this ambitious effort.
> docs(pt): update `i18n/pt-PT.js` content

- content/en/docs/5.configuration-glossary/15.configuration-ignore.md
- content/es/docs/5.configuration-glossary/15.configuration-ignore.md
- content/fr/docs/5.configuration-glossary/15.configuration-ignore.md
- content/ja/docs/5.configuration-glossary/15.configuration-ignore.md
- content/pt-br/docs/5.configuration-glossary/15.configuration-ignore.md
- content/pt/docs/5.configuration-glossary/15.configuration-ignore.md
After reviewing line 160 of /dist/config.js, I observed that spec files were included, hence I proceeded to add them.
https://www.npmjs.com/package/@nuxt/config?activeTab=code
> docs: update-docs-configuration-ignore.md

- content/pt/docs/1.get-started/1.installation.md
- content/pt/docs/1.get-started/2.routing.md
- content/pt/docs/1.get-started/3.directory-structure.md
- content/pt/docs/1.get-started/4.commands.md
- content/pt/docs/1.get-started/5.conclusion.md
- content/pt/docs/1.get-started/6.upgrading.md
- content/pt/docs/2.concepts/index.md
In this pull request, I am updating the translated content inside the `get-started` folder. This update consists in various grammar improvements and in the application of more descriptive words.
I also decided to signal progress and the desire to update the contents of the next folder by setting the `title: Conceitos` property in the `concepts/index.md` file.
I hope that this request to update the repository finds you in good health, and that this same request is combined with the main branch as soon as possible so that I can move forward more quickly with the rest.
Not only that, but I want to start translating the official Nuxt 3 documentation soon. I don't want to do it without first connecting the language used to communicate Nuxt 2 knowledge with Nuxt 3, and consequently updating the …
> docs(pt): update `get-started` folder and `concepts/index.md` file

- content/pt/docs/4.directory-structure/1.nuxt.md
- content/pt/docs/4.directory-structure/10.plugins.md
- content/pt/docs/4.directory-structure/11.static.md
- content/pt/docs/4.directory-structure/12.store.md
- content/pt/docs/4.directory-structure/13.nuxt-config.md
- content/pt/docs/4.directory-structure/2.assets.md
- content/pt/docs/4.directory-structure/3.components.md
- content/pt/docs/4.directory-structure/4.content.md
- content/pt/docs/4.directory-structure/5.dist.md
- content/pt/docs/4.directory-structure/6.layouts.md
- content/pt/docs/4.directory-structure/7.middleware.md
- content/pt/docs/4.directory-structure/8.modules.md
- content/pt/docs/4.directory-structure/9.pages.md
- content/pt/docs/4.directory-structure/index.md
In this request to update the main branch of the repository, I'm sending the changes applied to the contents of the `directory-structure` folder in the Portuguese documentation.
I know that some may consider it a waste of time to update this material, but I believe that anyone who thinks this way has no real idea of how many existing projects still use Nuxt 2. 
Depending on the size of the project, there is a lot of bureaucracy and effort to overcome before you can start thinking about updating the technology stack.
My reasons go a little further than the points mentioned above, because I also want to standardise the language with the one I'll be using to translate the Nuxt 3 website.
> docs(pt): update content inside `directory-structure` folder
