components/Affix.vue

Thematic, and don't look like they expand sections ( > V )

Change list markers

---

assets/scss/icons/_flags.scss

Fix flag icons centering

---

components/Affix.vue

Exchanged Tipe with Storyblok Logo and Link in Affix.vue

Updates Affix.vue

---

assets/scss/theme/_promote.scss

This CSS is needed to style the upcoming PR's to the Nuxt.js documentation.
The style is subtle and inspired by the existing styles of your alerts (explicitly .Alert.Alert--light).
I've attached a [screenshot](https://i.imgur.com/QfpBBFD.png) for your convenience.

Create style and icon for video banner

---

.gitignore
modules/docs/index.js
modules/docs/renderer.js
modules/docs/server.js
nuxt.config.js

- Server is rewritten into a reusable class: [server.js](https://github.com/nuxt/nuxtjs.org/blob/refactor/improve-module/modules/docs/server.js)
- Module simplified: [index.js](https://github.com/nuxt/nuxtjs.org/blob/refactor/improve-module/modules/docs/index.js)
- General refactor and improvements
TODO: 
- Speed-up generate
- Try regex approach

refactor: improve module

---

components/HeaderNavMenu.vue

nav element is opened and closed cleanly

nav element is opened and closed cleanly

---

assets/css/tailwind.css

fix: purgecss ignore sticky class

---

components/partials/Header.vue

Changed mobile navigation links to be full size

---

components/partials/home/welcome.vue

This PR is part 2 of https://github.com/nuxt/nuxtjs.org/issues/263. In addition to this PR, I created another PR (https://github.com/nuxt/docs/pull/1653).
Using store instead of hard-coded wordings in welcome section.

Update the welcome section to enable translations

---

components/commons/Select.global.vue
components/partials/Footer.vue
components/partials/Header.vue
mixins/localeManager.js

Addresses #272 and Firefox navbar layout issue mentioned in #278 (tried to create new issue via reference but got automatically closed by bot).
Tested on latest Edge/Chrome/Firefox/Safari via Browserstack.

Fixes issue regarding firefox's rendering of navbar, added slim version of language switch to navbar

---

.gitpod.Dockerfile
.gitpod.yml
README.md

Hello :smiley:,
This PR Simplifies Code Contributions by automating development environment setup with Gitpod (A free online VSCode like IDE running in the browser) with a single click it will launch a ready to code workspace with all the dependencies pre-installed, and will run the server, and modify /etc/hosts as needed
Try it out 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/JesterOrNot/nuxtjs.org/tree/gitpod)

Simplify Contribution with Gitpod

---

components/partials/Aside.vue
components/partials/DarkModeToggle.vue
components/partials/home/companies.vue
components/partials/home/sponsors.vue
pages/sponsor-nuxtjs.vue
tailwind.config.js

In Firefox flexbox centering is missing.

WIP: fix: Firefox dark mode toggle flexbox centering

---

components/partials/Aside.vue
components/partials/DarkModeToggle.vue
tailwind.config.js

Fix color mode toggle flexbox.

fix: color mode toggle

---

components/partials/Header.vue
components/partials/MobileMainNavigation.vue

temporary filter out Blog links from navigation

hotfix: temp filter out blog links

---

components/partials/NewsletterForm.vue

fixes #331
Implements @manniL idea to make newsletter anchor
Made `id` more verbose to prevent possible conflicts in future

feature: newsletter anchor

---

components/commons/blog/postItem/postItem.global.vue
components/commons/blog/postPreviewItem/postPreviewItem.global.vue
yarn.lock

Currently this is what happens on small screens:
I've implemented the following solution which adds a wrapper div:
Another option (let me know what you think) is this one which is just CSS:

Align tags for small screens

---

components/partials/home/HomeCompanies.vue
components/partials/home/HomeModes.vue
components/partials/home/HomeWelcome.vue
components/partials/home/HomeWhy.vue
layouts/default.vue
nuxt.config.js
pages/_section.vue
pages/blog/_slug.vue
pages/blog/index.vue
pages/design.vue
pages/resources.vue
pages/shop.vue
pages/sponsor-nuxtjs.vue
pages/support.vue
pages/team.vue
pages/themes.vue
pages/video-courses.vue
tailwind.config.js

Fixes route transition delay described in issue #365 .

fix: route transition delay

---

components/partials/home/HomeWelcome.vue

---
Alternatively (instead of deleting) we could fill that part with a paragraph again.

fix(home): title is shown twice

---

pages/team.vue

**Small changes**:
* fixed twitter link
* updated website links (removed sites that 404) and added sites that weren't present, if I could find them
* added `https` where possible
* corrected `developper` typo

fix: team updates

---

pages/team.vue

Holland is not a country, it should be The Netherlands :netherlands: :orange_heart: 
This is borderline blasphemy! :upside_down_face:

chore: use actual country name

---

content/en/api/configuration-build.md

The option introduced in https://github.com/nuxt/nuxt.js/pull/7785

docs: add corejs option to configuration build docs

---

content/en/guides/get-started/upgrading.md

`target:static` property should be set in nuxt.config.js rather than package.json file.

Fix filename for setting the target property

---

content/en/guides/get-started/installation.md
content/fr/guides/get-started/installation.md

Messes up the syntax highlighting in the docs :)

Fix yarn with capital Y

---

content/en/guides/configuration-glossary/configuration-build.md

Added a link to the Nuxt@2.14 tag
Added a warning to using non-hashed filenames

Updated a link and added a warning

---

i18n/en-US.js
i18n/es-ES.js
i18n/fr-FR.js
i18n/id-ID.js
i18n/ja-JP.js
i18n/ko-KO.js
i18n/ru-RU.js
i18n/zh-ZH.js
pages/design.vue
pages/resources.vue
pages/shop.vue
pages/sponsor-nuxtjs.vue
pages/support.vue
pages/team.vue
pages/themes.vue
pages/video-courses.vue

Add the ability to translate the different pages on the same model as the homepage.

add: i18n to pages

---

i18n/en-US.js

Minor typo on English Performant section on landing page.

Update en-US.js with missing space

---

content/en/guides/concepts/context-helpers.md
content/en/guides/directory-structure/components.md

- Concept > Context and Helpers > Internals Glossary link
- Concept > Context and Helpers > nuxtserverinit link
- Directory structure > componets > fetch() hook link

Update internal links from absolute to relative

---

content/fr/api/configuration-env.md

fr: Update configuration-env.md

---

i18n/id-ID.js

This time I corrected the previous request

Fix Update id-ID.js

---

content/en/guides/get-started/directory-structure.md

Grammar Fix

---

content/ko/guides/get-started/installation.md

I have started small step to translate document into Korean.

ko: Translate installaion.md into Korean

---

content/en/guide/commands.md

Fixes inconsistent whitespace on the following page:
https://nuxtjs.org/guide/commands

Fix inconsistent whitespace

---

content/en/guides/get-started/routing.md
content/id/guides/get-started/conclusion.md
content/id/guides/get-started/directory-structure.md
content/id/guides/get-started/installation.md
content/id/guides/get-started/routing.md
content/id/guides/get-started/upgrading.md

Hi, I'm Andre from Indonesia.
I'm very happy with Nuxt.js ❤
I've read the Documentation in Bahasa Indonesia. I found a lot of sentences that looked stiff. I hope this helps.
I will also help translate other pages that have not yet been translated into Indonesian. Wait for my other Pull Request.
Thank you.
Regards,
Andre
Bdw, I have another Pull Request too for Updating the Routing Pages. I hope is not a spam. #516 😀

Update Guides/Get Started in Bahasa Indonesia

---

i18n/es-ES.js

I have edited to correct some mistakes in the translation.

[Spanish] translate new guides

---

content/es/guides/components-glossary/pages-fetch.md

docs: translated pages-fetch guide to spanish

---

content/es/guides/components-glossary/pages-head.md

docs: translated pages-head guide to spanish

---

content/sp/guides/components-glossary/pages-key.md
content/sp/guides/components-glossary/pages-layout.md

Hello everybody! Here is my first collaboration translating docs to spanish.

docs: pages-key spanish translation

---

content/es/guides/get-started/conclusion.md
nuxt.config.js

Translating content/es/guides/get-started/conclusion.md into Spanish

---

i18n/fr-FR.js

Hi, 
Here is a simple contribution to continue to translate french documentation. 
i18n configuration
[x] i18n file
Enjoy it :) 
Next coming soon ;)

docs: french translatation of i18n

---

pages/team.vue

Change location after moving ☺️

chore(team): change location of Alexander Lichter

---

content/pt/guides/directory-structure/components.md
content/pt/guides/directory-structure/modules.md
i18n/pt-BR.js

- Applied changes made on this [commit](https://github.com/nuxt/nuxtjs.org/commit/b378676d644c394cd066073217f934c1783cf437)
-  Fix typo on guides/directory-structure/components and pt-BR i18n file

docs(pt-br): update docs to reflect changes and fix some typos

---

content/pt/guides/features/live-preview.md

docs(pt-br): add information to preview mode (#534)

---

content/fr/guides/get-started/conclusion.md
content/fr/guides/get-started/directory-structure.md
content/fr/guides/get-started/routing.md
content/fr/guides/get-started/upgrading.md
i18n/fr-FR.js

French : translate all get started section

---

content/ja/guides/features/rendering-modes.md

I translated `features/rendering-modes.md`. please review this PR✨
**Ref**

docs(ja): translate guides/features/rendering-modes

---

assets/css/rtl.scss
components/partials/AlgoliaSearchInput.vue

fix: apply rtl styles for algolia when dir is `rtl`

---

content/en/blog/creating-blog-with-nuxt-content.md

While reading this excellent blog article, I've found some small typos and inconsequences. Fixing these could provide a better reading experience for future readers.

Fix small typos and tiny inconsistencies

---

content/ja/guides/features/deployment-targets.md

I translated `features/deployment-targets.md`. please review this PR✨
**Ref**

docs(ja): translate guides/features/deployment-targets

---

content/id/guides/directory-structure/assets.md

This is part of <a href="https://github.com/nuxt/nuxtjs.org/issues/549">#549</a>
Translate `guides/directory-structure` for Indonesia localization
See the <a href="https://github.com/nuxt/nuxtjs.org/compare/034e317..5d31800">most up to date diff</a> for faster review.

[docs-id] Translate guides/directory-structure/assets

---

content/id/guides/configuration-glossary/configuration-cli.md
content/id/guides/configuration-glossary/configuration-srcdir.md
content/id/guides/configuration-glossary/configuration-target.md

This is part of #549 
Translate `guides/configuration-glossary` for Indonesia

[docs-id] Translate guides/configuration-glossary

---

i18n/pt-BR.js

Translated the Footer links to pt-BR.

refactor(i18n): add footer translations to pt-br

---

content/id/guides/features/deployment-targets.md
content/id/guides/features/rendering-modes.md

Translation contribution for issue #549 
Files translated:
📝 guides -> features:

[docs-id] Translate guides/features

---

content/es/guides/configuration-glossary/configuration-mode.md
content/es/guides/configuration-glossary/configuration-modules.md
content/es/guides/configuration-glossary/configuration-modulesdir.md
content/es/guides/configuration-glossary/configuration-plugins.md

[SPANISH] Translate configuration glossary mode, modules and plugins

---

content/es/guides/configuration-glossary/configuration-hooks.md
content/es/guides/configuration-glossary/configuration-ignore.md
content/es/guides/configuration-glossary/configuration-loading-indicator.md
content/es/guides/configuration-glossary/configuration-loading.md

Pages translated to Spanish for #543
📝 guides -> configuration-glossary

[Spanish] Translate guides configuration glossary

---

content/en/guides/features/file-system-routing.md

Hoping that this tweak will make a slightly easier to read this part of the docs.

Tweak grammar for Dynamic Nested Routes

---

content/ja/guides/features/live-preview.md

I translated `features/live-preview.md`. please review this PR✨
**Ref**

docs(ja): translate guides/features/live-preview

---

content/ja/guides/features/transitions.md

I translated `features/transitions.md`. please review this PR✨
**Ref**

docs(ja): translate guides/features/transitions

---

content/fa/guides/get-started/installation.md
i18n/fa-IR.js

Translation of the following document guides/get-started/installation.md
and i18n/fa-IR.js ( footer object )

Translation to Farsi(Persian) - installation.md & fa-IR.js footer

---

content/en/guides/directory-structure/components.md

"Fix error: "Component template should contain exactly one root element.."

Fix structure of layouts.default.vue and path

---

content/en/guides/directory-structure/plugins.md

docs(plugins): fix md in alert

---

content/es/guides/concepts/server-side-rendering.md
content/es/guides/concepts/views.md
content/es/guides/directory-structure/modules.md

server-side-rendering
views
some in modules

i18n spanish: server-side-rendering

---

content/en/blog/creating-blog-with-nuxt-content.md

Scoped styles are possible with deep selectors

Update nuxt-content styling

---

content/ja/guides/get-started/routing.md

@inouetakuya @53able Could you review this PR when you're available? Thank you.

docs(ja): translate guides/get-started/routing

---

content/ja/guides/get-started/upgrading.md

@inouetakuya @53able Could you review this PR when you're available? Thanks.

docs(ja): translate guides/get-started/upgrading

---

content/ja/guides/configuration-glossary/configuration-css.md

docs(ja): translate guides/configuration-glossary/configuration-css

---

content/ja/guides/configuration-glossary/configuration-components.md

docs(ja): translate guides/configuration-glossary/configuration-components

---

content/ja/guides/configuration-glossary/configuration-cli.md

docs(ja): translate guides/configuration-glossary/configuration-cli

---

content/ja/guides/configuration-glossary/configuration-builddir.md

docs(ja): translate guides/configuration-glossary/configuration-builddir

---

content/ja/guides/configuration-glossary/configuration-build.md

docs(ja): translate guides/configuration-glossary/configuration-build

---

content/en/blog/creating-blog-with-nuxt-content.md

Reference: https://content.nuxtjs.org/writing#vue-components

Edit nuxtjs.org/content/en/blog/creating-blog-with-nuxt-content.md

---

content/ja/guides/components-glossary/pages-loading.md

@aytdm @53able Could you review this PR?
refs

docs(ja): translate guides/components-glossary/pages-loading

---

content/ja/guides/configuration-glossary/configuration-mode.md

- https://ja.nuxtjs.org/api/configuration-mode

docs(ja): translate guides/configuration-glossary/configuration-mode

---

content/ja/guides/configuration-glossary/configuration-global-name.md

- https://ja.nuxtjs.org/api/configuration-global-name

docs(ja): translate guides/configuration-glossary/configuration-global-name

---

content/ja/guides/configuration-glossary/configuration-ignore.md

- https://ja.nuxtjs.org/api/configuration-ignore

docs(ja): translate guides/configuration-glossary/configuration-ignore

---

content/ja/guides/features/meta-tags-seo.md

I translated `features/meta-tag-seo.md`. please review this PR✨
**Ref**

docs(ja): translate guides/features/meta-tag-seo

---

content/en/guides/directory-structure/nuxt-config.md

replace some confusing slashes with ,

---

content/es/guides/concepts/context-helpers.md
content/es/guides/concepts/nuxt-lifecycle.md
content/es/guides/directory-structure/nuxt-config.md
content/es/guides/directory-structure/plugins.md

I wish finish my Hacktoberfest, please add "hacktoberfest-accepted" tag to the PR.
In this PR:
- Update plugins.md
- Apply to spanish
- https://github.com/nuxt/nuxtjs.org/commit/aee711c31cfefe2c328607f84601154721a9a86c
- https://github.com/nuxt/nuxtjs.org/commit/7950dbca53fb705a4ad10393759b8dd1d848d3dc
- https://github.com/nuxt/nuxtjs.org/commit/a79318f97f7ace6897944d6e328c9be55209efe9

docs(es): Update spanish

---

content/en/blog/nuxt-static-improvements.md

Updated Twitter profile image url 🙈 
Ref: https://nuxtjs.org/blog/nuxt-static-improvements

fix: broken avatar url

---

content/ja/guides/get-started/conclusion.md
content/ja/guides/get-started/upgrading.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/166

docs(ja): fix position

---

_redirects

issues detected with script in #955
closes #953 (partly) as link will now be valid

fix: redirect to valid urls

---

content/en/_archives/api/configuration-build.md
content/en/_archives/api/configuration-rootdir.md
content/en/blog/creating-blog-with-nuxt-content.md
content/en/blog/moving-from-nuxtjs-dotenv-to-runtime-config.md
content/en/faq/surge-deployment.md
content/en/guides/concepts/context-helpers.md
content/en/guides/configuration-glossary/configuration-build.md
content/es/guides/concepts/context-helpers.md
content/es/guides/configuration-glossary/configuration-build.md
content/fr/api/configuration-build.md
content/id/api/configuration-build.md
content/id/guides/concepts/context-helpers.md
content/ja/api/configuration-build.md
content/ja/guides/configuration-glossary/configuration-build.md
content/ko/guides/concepts/context-helpers.md
content/pt/guides/concepts/context-helpers.md
content/pt/guides/configuration-glossary/configuration-build.md
content/zh/api/configuration-build.md

Broken links flagged up by script in #955

fix: broken links

---

components/organisms/MasteringNuxtBanner.vue

This pr updates the text of the Mastering Nuxt banner.
Please see the attached screenshot for the visual appearance.

Update text on Mastering Nuxt banner

---

content/ru/guides/concepts/views.md

Added translate "concepts/views" for RU

docs(ru): Translate directory concepts

---

content/ru/guides/concepts/views.md
content/ru/guides/features/live-preview.md

Added translate "features/live-preview" for RU

docs(ru): Translate directory features 

---

content/ja/guides/configuration-glossary/configuration-render.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/107
Ref: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/api/configuration-render.md

docs(ja): translate configuration-render

---

content/ja/guides/configuration-glossary/configuration-rootdir.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/133
Ref: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/api/configuration-rootdir.md

docs(ja): translate configuration-rootdir

---

content/ja/guides/configuration-glossary/configuration-runtime-config.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/141

docs(ja): translate configuration-runtime-config

---

content/en/guides/configuration-glossary/configuration-render.md

See https://github.com/nuxt/nuxt.js/pull/8347

docs(en): add info on new `render.asyncScripts` option

---

content/id/guides/components-glossary/pages-transition.md
content/id/guides/components-glossary/pages-validate.md
content/id/guides/components-glossary/pages-watchquery.md
content/id/guides/features/configuration.md
content/id/guides/features/data-fetching.md
content/id/guides/internals-glossary/nuxt-render.md
pages/docs/2.x/_book.vue
pages/docs/2.x/_book/_slug.vue
pages/docs/release-notes.vue

These 3 languages are very far advanced with translations and are ready to be merged so they are visible. Any missing pages will fallback to English and translators can then easily pick them up and translate

feat: fr, id, ja translations live

---

content/en/guides/directory-structure/modules.md

Small grammar issue with `and will resolved`. Changed to `and will resolve`

Fix: improper verb conjugation

---

lambda/webhook.js

@danielroe 😃lets see if it works

fix: require instead of import

---

content/en/guides/features/nuxt-components.md

link to blog instead of linking to itself

fix: link to blog

---

content/en/guides/features/transitions.md

Fix typo in code chunk

---

content/en/blog/creating-a-nuxt-module.md

Also added the fix to https://github.com/nuxt-academy/examples/pull/1

fix: correct url path -> $config.ngrok.url

---

content/ja/guides/features/transitions.md

Please review [vuejs-jp#211](https://github.com/vuejs-jp/ja.nuxtjs.org/issues/211)

docs(ja): fix typo in code chunk

---

content/ja/guides/configuration-glossary/configuration-server.md

Ref: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/_archives/api/configuration-server.md
resolve vuejs-jp#142

docs(ja): translate configuration-server

---

content/ja/guides/configuration-glossary/configuration-rootdir.md

resolves https://github.com/vuejs-jp/ja.nuxtjs.org/issues/215, resolves https://github.com/vuejs-jp/ja.nuxtjs.org/issues/217

docs(ja): fix link rootdir

---

content/ja/guides/get-started/installation.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/208
rel: https://github.com/nuxt/nuxtjs.org/pull/756, https://github.com/nuxt/nuxtjs.org/pull/837

docs(ja): fix get-started/installation

---

content/en/examples/seo-twitter-og.md

new example for twitter / og social charing

docs: twitter og example

---

i18n/pt-BR.js

docs(pt-br) Update bottom documentation pt-br

---

content/ja/guides/configuration-glossary/configuration-servermiddleware.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/136, resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/127
ref: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/_archives/api/configuration-servermiddleware.md

docs(ja): translate configuration-servermiddleware

---

content/en/guides/directory-structure/static.md

I filled correct answer of question and remove extra single quotation.

docs(en): fix directory-structure/static

---

_redirects
content/en/faq/vercel-deployment.md
content/fr/faq/vercel-deployment.md
content/ja/faq/vercel-deployment.md
content/ko/faq/vercel-deployment.md
content/ru/_archives/guide/commands.md
content/zh/faq/vercel-deployment.md

docs: update references now -> vercel + clarify vercel-builder is for SSR

---

content/en/guides/configuration-glossary/configuration-router.md

relates to https://github.com/nuxt/nuxt.js/pull/8423

docs(en): add example behaviour for child routes with `trailingSlash`

---

content/ja/guides/configuration-glossary/configuration-telemetry.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/134

docs(ja): translate configuration-telemetry

---

content/ja/guides/configuration-glossary/configuration-router.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/140
rel: https://github.com/nuxt/nuxtjs.org/blob/master/content/ja/_archives/api/configuration-router.md

docs(ja): translate configuration-router

---

content/en/guides/features/file-system-routing.md

Fixed a small typo in this section.

Update "Unknown Dynamic Nested Routes"

---

components/organisms/SponsorsBlock.vue
components/templates/home/HomeSponsors.vue

feat: ship shape sponsor

---

content/en/guides/configuration-glossary/configuration-build.md
content/en/guides/configuration-glossary/configuration-router.md

Matches https://github.com/nuxt/nuxt.js/pull/8520

docs(en): add info about dynamic config

---

README.md
pages/examples/_slug.vue

add chinese lang to array for examples
remove info on chinese translation from readMe as not active anymore

fix: chinese examples

---

content/en/guides/components-glossary/pages-fetch.md

* relates to https://github.com/nuxt/nuxt.js/pull/8466

docs: add documentation for `fetchKey`

---

content/ja/guides/directory-structure/assets.md
content/tr/guides/components-glossary/pages-fetch.md
content/tr/guides/components-glossary/pages-layout.md
content/tr/guides/components-glossary/pages-loading.md
content/tr/guides/components-glossary/pages-scrolltotop.md

parsing issues in yaml description on translated files.

fix: parsing issues

---

content/en/faq/deploying-to-21yunbox.md

As required to open a PR here, https://github.com/nuxt/docs/pull/2132

docs(en): deploy on 21YunBox

---

content/en/guides/configuration-glossary/configuration-servermiddleware.md

warn about adding serverMiddleware to middleware directory

docs: serverMiddleware warn

---

content/en/_archives/api/configuration-build.md

introduced in https://github.com/nuxt/nuxt.js/pull/6272

documented new loadingSreen property

---

content/en/guides/internals-glossary/internals-module-container.md

remove extendPlugin as not available for Modules

docs: remove extendPlugin

---

components/templates/blog/BlogpostPreviewItem.vue

Fix: Add space between post date and readingTime

---

content/en/faq/pre-processors.md
content/en/guides/configuration-glossary/configuration-css.md
content/en/guides/directory-structure/assets.md
content/en/guides/features/configuration.md

docs: add `fibers` explanation

---

content/en/guides/features/data-fetching.md

https://github.com/nuxt/nuxtjs.org/issues/533

Added mixin warning

---

content/en/guides/configuration-glossary/configuration-alias.md
content/en/guides/directory-structure/nuxt-config.md

I don't know if this documentation is correct, please help :fearful:

feat: add alias section to nuxt-config page

---

content/en/guides/directory-structure/nuxt-config.md

docs: add info on `--dotenv` cli option

---

components/templates/TheFooter.vue
components/templates/TheHeader.vue
components/templates/TheMobileBottomNav.vue
nuxt.config.js
pages/index.vue

imrovements from running lighthouse test and fixing issues including adding a pwa theme color as warning given for it on lighthouse 7

fix: performance issues

---

content/en/guides/get-started/installation.md

Double asterisks outside the line was causing italic and I moved them inside the square brackets.
Line Fixed:
The application is now running on *[http://localhost:3000](http://localhost:3000/).*

Fixed the typo causing italic instead of bold

---

content/en/guides/deployment/deployment-platformsh.md

Another PaaS host that makes hosting Nuxt easy.  I'm not sure what the position value should be, nor if you're OK with the particular formatting for the deploy button.  I can change both if you advise what they should be changed to.
Cheers.

Add deploy instructions for Platform.sh

---

content/en/guides/deployment/cleavr-deployment.md
content/en/guides/deployment/deploying-to-do-app-platform.md

Added a guide for deploying Nuxt SSR and Static apps using Cleavr. I also updated the order position of the DO guide so that they appear alphabetically.

Deploy with Cleavr guide

---

content/en/guides/directory-structure/assets.md

Added the keyboard shortcut for '~' on Windows

---

content/en/guides/get-started/commands.md

docs: text improvements

---

content/en/blog/build-dev-to-clone-with-nuxt-new-fetch.md
content/en/guides/configuration-glossary/configuration-css.md
content/en/guides/directory-structure/assets.md
content/en/guides/features/configuration.md
content/es/guides/configuration-glossary/configuration-css.md
content/es/guides/directory-structure/assets.md
content/es/guides/features/configuration.md
content/fr/faq/pre-processors.md
content/id/guides/directory-structure/assets.md
content/id/guides/features/configuration.md
content/ja/faq/pre-processors.md
content/ja/guides/configuration-glossary/configuration-css.md
content/ja/guides/directory-structure/assets.md
content/ko/guides/features/configuration.md
content/pt/guides/configuration-glossary/configuration-css.md
content/pt/guides/directory-structure/assets.md
content/pt/guides/features/configuration.md
content/zh/faq/pre-processors.md
renovate.json

https://github.com/nuxt/nuxt.js/issues/8771

docs: update `sass-loader` recommendation to v10

---

content/id/guides/internals-glossary/$nuxt.md

This is part of #549 
Translate `guides/internals-glossary` to Indonesian

docs(id): translate $nuxt.md to Indonesian

---

components/global/AppModal.vue
components/global/CodeGroup.vue
components/molecules/AppLangSelect.vue
components/organisms/NewsletterForm.vue
components/organisms/ReleaseNotes.vue
components/organisms/ads/CarbonAds.vue
components/templates/TheMobileAsideNav.vue
components/templates/TheMobileAsideNavNewDocs.vue
components/templates/home/HomeModes.vue
components/templates/home/HomeTargets.vue
components/templates/home/HomeWhy.vue
nuxt.config.js
package.json
pages/blog/_slug.vue
pages/blog/index.vue
pages/design.vue
pages/docs/release-notes.vue
pages/shop.vue
pages/support.vue
yarn.lock

feat: add plausible

---

content/en/guides/deployment/netlify-deployment.md

github has updated it default branch name to `main`

update default github branch name

---

content/en/guides/internals-glossary/nuxt-render-and-get-window.md

docs: update renderAndGetWindow example

---

content/en/_archives/api/configuration-generate.md
content/en/guides/configuration-glossary/configuration-generate.md

Add to generator.nojekyll options about https://github.com/nuxt/nuxt.js/pull/8813

docs(generate): add nojekyll option in generator

---

i18n/id-ID.js

Part of https://github.com/nuxt/nuxtjs.org/issues/549
cc: @febrihidayan

docs(id): translate untranslated thing in id-ID.js

---

content/id/guides/configuration-glossary/configuration-ignore.md
content/id/guides/configuration-glossary/configuration-mode.md
content/id/guides/configuration-glossary/configuration-plugins.md
content/id/guides/configuration-glossary/configuration-rootdir.md

docs(id): Translate configuration glossary

---

content/id/guides/configuration-glossary/configuration-loading-indicator.md
content/id/guides/configuration-glossary/configuration-loading.md
content/id/guides/configuration-glossary/configuration-server.md

docs(id): Translate configuration-glossary

---

i18n/es-ES.js
i18n/fa-IR.js
i18n/id-ID.js
i18n/ja-JP.js
i18n/ko-KO.js
i18n/pt-BR.js
i18n/ru-RU.js
i18n/tr-TR.js
i18n/zh-ZH.js

closes https://ptb.discord.com/channels/473401852243869706/473406506579263488/820250174588583947

fix: update header link from `/faq` to `/resources`

---

content/en/guides/directory-structure/modules.md

removing an unnecessary closing bracket.

fix: removed unnecessary closing bracket in code

---

_redirects
content/en/_archives/api/configuration-server.md
content/en/guides/get-started/commands.md
content/fr/_archives/api/configuration-server.md
content/ja/_archives/api/configuration-server.md
content/ko/_archives/api/configuration-server.md
content/zh/_archives/api/configuration-server.md
content/zh/guide/commands.md
content/zh/guide/index.md

issue on commands page reported via Discord

docs: update some faq links

---

content/en/guides/features/data-fetching.md

Even though the `fetch` hook is presented on the same page, I think it's best not to confuse the reader by suggesting "old" ways to fetch server-side data on component level.

chore(docs): server-side data fetching in components using fetch hook

---

content/en/guides/directory-structure/content.md
content/es/guides/directory-structure/content.md
content/fr/guides/directory-structure/content.md
content/id/guides/directory-structure/content.md
content/ja/guides/directory-structure/content.md
content/pt/guides/directory-structure/content.md

- `/fetching#api` to `/advanced/#api-endpoint`
- ref: https://content.nuxtjs.org/advanced/#api-endpoint
- `/advanced#integration-with-nuxtjsfeed` to `/integrations#nuxtjsfeed`
- ref: https://content.nuxtjs.org/integrations/#nuxtjsfeed

docs: update content module's link

---

content/ja/guides/directory-structure/content.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/122

docs(ja): translate directory-structure/content

---

content/en/blog/creating-blog-with-nuxt-content.md

Removed the extra "and" from second line of heading "Live editing our content".

removed extra "and" in sentence

---

content/fr/guides/internals-glossary/internals.md

fixed a broken link in French documentation

updated fr documentation broken link

---

i18n/ja-JP.js

I translated `i18n/ja-JP` into Japanese.
ref: https://github.com/nuxt/nuxtjs.org/issues/544#issue-684667241

docs(ja): translate i18n

---

content/ja/guides/directory-structure/modules.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/144

docs(ja): translate directory-structure/modules

---

content/ja/guides/directory-structure/layouts.md
content/ja/guides/directory-structure/pages.md
content/ja/guides/features/configuration.md
content/ja/guides/features/data-fetching.md
content/ja/guides/features/file-system-routing.md
content/ja/guides/features/loading.md
content/ja/guides/features/meta-tags-seo.md
content/ja/guides/features/nuxt-components.md
content/ja/guides/features/transitions.md

対象が多くてすみませんがレビューよろしくお願いします:bow:
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/176
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/177
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/178
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/179
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/180
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/181
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/182
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/192
resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/220

docs(ja): add translate for question

---

content/en/guides/configuration-glossary/configuration-build.md

Explaining what the example means also explains what `isModern` and `isLegacy` means.

Add example explanation for transpile

---

components/organisms/SponsorsBlock.vue

This PR fixes the link to the strapi.io website.

Fix Strapi link

---

content/en/guides/get-started/commands.md

Just a missing opening bracket.!!

docs: add missing opening bracket

---

content/ja/guides/configuration-glossary/configuration-srcdir.md

resolved #1421.
resolved https://github.com/vuejs-jp/ja.nuxtjs.org/issues/298
Please check it!

docs(ja): modify description about configuration-srcdir

---

content/en/guides/get-started/installation.md

Explanatory sentence about the asked questions has a missing parenthesis, that's all

Missing closing parenthesis

---

content/en/_archives/guide/modules.md
content/en/guides/directory-structure/modules.md
content/es/guides/directory-structure/modules.md
content/fr/_archives/guide/modules.md
content/fr/guides/directory-structure/modules.md
content/id/_archives/guide/modules.md
content/id/guides/directory-structure/modules.md
content/ja/_archives/guide/modules.md
content/ja/guides/directory-structure/modules.md
content/ko/_archives/guide/modules.md
content/pt/guides/directory-structure/modules.md
content/zh/guide/modules.md

docs: change module function name to match purpose

---

content/en/guides/get-started/installation.md

Updating the syntax for bonus step alert to give it a more precise meaning.

Updating the information alert under "Bonus Step"

---

content/en/guides/get-started/installation.md

Just updating the nuxt installation prerequisites.

docs: update nuxt prerequisites

---

content/en/_archives/guide/vuex-store.md
content/en/guides/directory-structure/store.md

I believe 
> **add** the authenticated user to to our store
would be more accurate here.

style: tiny rephrase in docs / store example

---

content/en/guides/deployment/vercel-deployment.md
content/ja/_archives/faq/vercel-deployment.md

fix: Vercel deployment with PWA module example

---

pages/team.vue

It seems like there's some auto formatting happening for the CSS styles that I'm not committing myself. Hope this is alright!

docs: add ben to ambassador list

---

content/en/guides/deployment/deployment-fume.md

Hoping to get fume listed as a valid option!

📝 add Fume to the list of deployment options

---

content/ja/guides/deployment/cleavr-deployment.md

docs(ja): translate deployment/cleavr-deployment

---

content/en/_archives/api/configuration-router.md
content/en/guides/configuration-glossary/configuration-router.md
content/es/guides/configuration-glossary/configuration-router.md
content/fr/guides/configuration-glossary/configuration-router.md
content/ja/guides/configuration-glossary/configuration-router.md
content/pt/guides/configuration-glossary/configuration-router.md

Changing `prefetchPaylods` to `prefetchPayloads`.

fix typo of prefetchPaylods

---

content/en/guides/features/configuration.md

This tripped me up for a long time, hopefully you will accept this small addition to the docs.

Add note about script lang for typescript JSX

---

content/ja/guides/deployment/deploying-to-21yunbox.md

docs(ja): translate deployment/deploying-to-21yunbox

---

content/es/guides/directory-structure/pages.md

Just deleted the same paragraph left in english in the spanish doc

minor-typo fix

---

content/fr/index.md

Petites corrections de la version française, même si j'imagine que le texte n'est pas encore définitif !

Index page FR translations

---

components/atoms/icons/IconExternalLink.vue
components/organisms/app/HeaderNavigation.vue

Adding a component icon for externals links on hover  and refactorisation headerNavigation

feat: new component for externals links

---

components/organisms/ContentCardTemplate.vue
components/organisms/home/HomeCampfire.vue
components/organisms/resources/ResourcesList.vue
components/organisms/section/SectionContentItem.vue

related to [https://github.com/nuxtlabs/nuxtjs.org-board/issues/136](url)

fix: remove localPath to external links

---

components/templates/Releases.vue

related to [https://volta.net/nuxtlabs/nuxtjs.org-board/issues/140](url)

refacto: releases page

---

content/fr/guides/directory-structure/modules.md

Hi, 
A little sentence forgotten on the french module page ;)

docs: remove english sentence on french module page

---

components/atoms/icons/IconExternalLink.vue
components/organisms/app/HeaderNavigation.vue
content/en/teams/2.community.md
content/fr/teams/2.community.md

Adding new members (Kévin Marrec)
@Flosciante

docs: adding members

---

package.json
scripts/crawl.ts
yarn.lock

Will check all URLs on `nuxtjs.org` to ensure matching URLs or redirects exist on `preview.nuxtjs.org`. Will need to be used manually but could add a GitHub Action to check preview links.
**Usage**:
```
./scripts/crawl.ts
```

chore: add script to ensure corresponding pages/redirects exist

---

content/en/0.docs/8.deployment/25.Stormkitio.md

Here's [the PR](https://github.com/nuxt/nuxtjs.org/pull/1563) I opened against the `main` branch. As requested, I'm opening a new PR against the `preview` branch 🙏

Update Stormkit documentation

---

nuxt.config.js

Quick single character update to the website!

Changed number of stars from 34k to 37k

---

content/en/guides/configuration-glossary/configuration-env.md

Fix small typo

---

components/organisms/MasteringNuxtBanner.vue

Please merge after Aug 3rd 00.00 CEST 🚀

Update mastering nuxt banner

---

package.json
yarn.lock

resolves nuxtlabs/nuxtjs.org-board#172

chore: update docus

---

content/ja/guides/deployment/deployment-azure-static-web-apps.md

Please review this PullRequest.
ref vuejs-jp#251

docs(ja): translate deployment/deployment-azure-static-web-apps

---

content/ja/guides/deployment/deployment-cloud-run.md

Please review this PullRequest.
ref vuejs-jp#251

docs(ja): translate deployment/deployment-cloud-run

---

content/ja/guides/configuration-glossary/configuration-build.md

docs(ja):fix markdown typo

---

components/organisms/NuxtNationBanner.vue
layouts/default.vue

This PR adds the [nuxtnation.com](https://nuxtnation.com) promotional banner.
The banner is closable, and the closed state is stored in local storage.
[Please check these screenshots and screencasts here.](https://imgur.com/a/LOrOe80)

Added Nuxt Nation banner for the September conference

---

components/organisms/NuxtNationBanner.vue

nested `<a>` tags are invalid html and was causing a hydration error

fix: remove nested `<a>` tag

---

content/ja/guides/internals-glossary/internals-module-container.md

docs(ja): add missing comma to addPlugin code example

---

content/en/guides/configuration-glossary/configuration-servermiddleware.md

bodyParser is deprecated in express 4.16+

docs: bodyParser is deprecated

---

content/en/guides/features/configuration.md

This PR adds consistent formatting to tokens, directories and file references.

Consistent formatting

---

content/en/0.docs/4.directory-structure/8.modules.md
content/en/0.docs/5.configuration-glossary/20.configuration-modules.md

See: https://github.com/nuxt/nuxtjs.org/pull/1622

docs: add note on modules using plugins

---

components/molecules/ModulesCard.vue
components/molecules/ads/AdsCarbon.vue
components/molecules/footer/FooterFoot.vue
components/molecules/footer/FooterLink.vue
components/molecules/footer/FooterNewsLetter.vue
components/molecules/footer/FooterSocialLinks.vue
components/organisms/ContentCardTemplate.vue
components/organisms/app/AppFooter.vue
components/organisms/app/AppHeader.vue
components/organisms/blog/BlogpostList.vue
components/organisms/home/HomeTestimonials.vue
components/organisms/modules/ModulesListing.vue
components/organisms/showcases/ShowcasesCard.vue

First pass on LightHouse audit.
- Some color contrasts may need to be fixed, tertiary texts are not consistant across the website.
- Some `description` meta are missing.
- `rel=preload` are needed on many things but I cannot find a way to fix it even on the nuxtConfig main font (`rel=preload, as=style` does not work).
- And finaly but mainly, performances are pretty bad. I guess pictures and animations are the main concern.
Merging this on preview will give us a more accurate score.

chore(lighthouse): first pass of optimisations

---

content/.new/.1.learn/1.usage/7.modules.md

Based on https://github.com/nuxt/nuxtjs.org/pull/1619#issuecomment-911827735  
> Thank you, it would be awesome if you could also apply the changes to the preview branch 😊

docs: add options usage to example

---

components/atoms/icons/IconChevronBottom.vue
components/atoms/icons/IconClose.vue
components/theme/app/AppAside.vue
components/theme/app/AsideHeaderNavigation.vue
components/theme/app/AsideNavigation.vue
content/en/_collections/navigations/header.md
docus.config.ts

Resolves nuxtlabs/nuxtjs.org-board#185

feat(aside): customise Docus `Aside`

---

components/theme/app/AppLayout.vue
components/theme/app/AsideNavigation.vue

fix(AppLayout): use vue2 style computed

---

content/en/_collections/navigations/footer.md

fix: broken link

---

content/en/docs/4.directory-structure/6.layouts.md

Spelling error Nux ⇾ Nuxt

---

content/ja/index.md
content/ja/sponsors/index.md
content/ja/v3/index.md
i18n/ja-JP.js

ping @Atinux 
Sorry, for sending you a PR just before the event.

docs: more quick localizing

---

components/theme/app/AppLayout.vue

Remove `useFetch` composition API. Resolve issue with 404 page

fix(AppLayout): refactor composition api

---

content/en/case-studies/0.github.md

Updating a few minor things on the GitHub Stars case study. Thanks for putting this together for us @alexchopin and team!

Update GitHub Stars case study

---

assets/nuxt.css
components/molecules/forms/AlgoliaSearchBox.vue
components/theme/app/AppBanner.vue
components/theme/app/AppFooter.vue
components/theme/app/AppHeader.vue
components/theme/app/AsideHeaderNavigation.vue

Resolves nuxtlabs/nuxtjs.org-board#180

feat(accessibility): make focus rings green & only visible on tab focus

---

docus.config.ts

chore(docus): update GitHub default branch

---

content/en/docs/3.features/4.data-fetching.md

This PR give further explanation on how does `fetchKey` affect rendering.

docs: add explanation for use of `fetchKey`

---

components/theme/app/AppFooter.vue

fix: add titles for social icons

---

content/en/contribution-guide/index.md
content/fr/contribution-guide/index.md
content/ja/contribution-guide/index.md

fix: update Contribution Guide broken link

---

content/en/integrations/deployments/digital-ocean.md

- Update Web service configuration options and add a warning alert with the HTTP Port update.
- Added reference to the article that explains it.
Fixes #1731 
Thanks @spirico for the suggestion 🤗

Nuxt server deploy on DO App platform update

---

components/atoms/Logo.vue
components/atoms/links/HeaderNavigationLink.vue
components/atoms/selects/Dropdown.vue
components/molecules/forms/ColorSwitcher.vue
components/molecules/forms/LangSwitcher.vue
components/organisms/home/HomeFeatures.vue
components/organisms/lists/Testimonials.vue
components/theme/app/AppAside.vue
components/theme/app/AppBanner.vue
components/theme/app/AppFooter.vue
components/theme/app/AppHeader.vue
components/theme/app/AsideBottom.vue
components/theme/app/AsideHeaderNavigation.vue
nuxt.config.ts
plugins/nav.js

Should fix issues on broken UI due to a specific locale and color mode. Well tested with `nuxt generate`.

fix: url checks based on `route.path`

---

components/theme/app/AppLayout.vue
nuxt.config.ts
package.json
plugins/mq.js
yarn.lock

Resolves nuxtlabs/nuxtjs.org-board#216

fix(Aside): desktop AsideNavigation stickiness

---

components/global/BarChartCacheBuild.vue
components/global/BaseAlert.vue
package.json
windi.config.js
yarn.lock

Fixes nuxtlabs/nuxtjs.org-board#219
Components picked from `v2` branch
Concerned pages:
- https://nuxtjs.org/announcements/nuxt-static-improvements
- https://nuxtjs.org/announcements/going-full-static

fix: add missing components used in markdown

---

content/fr/contribution-guide/index.md

docs(fr): contribution-guide.md

---

components/organisms/home/HomeHero.vue

Resolves nuxtlabs/nuxtjs.org-board#228

fix(Home): `SectionButton`s spacing

---

content/en/docs/5.configuration-glossary/6.configuration-components.md

Shouldn't it be `Array` here instead of `Object`?

Change Object to Array

---

content/en/docs/3.features/2.deployment-targets.md

A server is also needed to serve static content. Server here means nodejs webserver or an equivalent javascript webserver environment that handles the js rendering.

fix(docs): Update server hosting informations

---

components/organisms/home/HomeFeatures.vue
components/organisms/home/HomeTestimonials.vue
components/organisms/lists/Testimonials.vue

fix(Homepage): mountains overing content

---

content/en/docs/3.features/6.configuration.md
content/fr/docs/3.features/6.configuration.md
content/ja/docs/3.features/6.configuration.md

fix(docs): update features > configuration

---

content/en/docs/1.get-started/5.conclusion.md
content/fr/docs/1.get-started/5.conclusion.md
content/ja/docs/1.get-started/5.conclusion.md

Issue: https://github.com/nuxt/nuxtjs.org/issues/1817

fix(docs): concepts book link on firefox

---

components/organisms/asides/AsideModules.vue
components/organisms/lists/ModulesListing.vue

fix(Modules): blink / fetch client slide

---

components/molecules/EditOnGithub.vue
components/molecules/cards/ContentCardTemplate.vue
components/molecules/cards/ShowcasesCard.vue
components/molecules/cards/SupportCard.vue
components/molecules/cards/SustainabilityCard.vue
components/molecules/cards/TeamMember.vue
components/organisms/design/DesignLogos.vue
components/organisms/home/HomeCampfire.vue
components/organisms/home/HomeDiscover.vue
components/organisms/sections/SectionContentItem.vue
components/organisms/sections/SustainabilityDetail.vue
components/templates/Events.vue
components/templates/Post.vue
components/theme/Error.vue
components/theme/blog/BlogpostList.vue
i18n/en-US.js
i18n/fr-FR.js

Add `loading="lazy"` on very `img` and `NuxtImg`

chore: add `loading="lazy"` on images

---

content/en/examples/9.plugins/1.vue.md

Corrects minor typo on import statement.

Fix: correct typo on Vue Plugins page

---

content/ja/docs/1.get-started/1.installation.md
content/ja/docs/5.configuration-glossary/25.configuration-router.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/380
翻訳しました、レビューお願いいたします。

docs(ja): grammar fixes in install guide and add scrollBehaviour note

---

content/ja/docs/3.features/4.data-fetching.md

resolve https://github.com/vuejs-jp/ja.nuxtjs.org/issues/383
翻訳しました、レビューお願いいたします。

docs(ja): add explanation for use of fetchKey

---

content/ja/docs/2.concepts/2.context-helpers.md

resolve vuejs-jp#381
翻訳しました、レビューお願いいたします

docs(ja): add definitions for acronyms + technical terms

---

content/en/docs/3.features/4.data-fetching.md

on route `/features/data-fetching`

docs: template should have only one child

---

components/molecules/EditOnGithub.vue

fix(contributors): API call

---

content/fr/docs/4.directory-structure/8.modules.md

fix(content): remove `en` in `fr` content + fix component

---

content/ja/index.md

resolve vuejs-jp#377
翻訳しました、レビューお願いいたします。

docs(ja): grammatical improvements

---

components/molecules/cards/LogoCard.vue
content/_collections/partners/technology/0.netlify.md

feat: add location to partners list cards

---

content/en/docs/5.configuration-glossary/2.configuration-build.md

Related to https://github.com/nuxt/framework/pull/2871

docs: fix typo in build.transpile docs

---

content/fr/docs/4.directory-structure/12.store.md

- missing translation on directory-structure/store

docs(fr): translate store directory structure

---

content/fr/docs/4.directory-structure/10.plugins.md

Quelques petites rectifications

Page plugins : typos

---

content/fr/docs/2.concepts/2.context-helpers.md

Petites typos et vérification cohérence avec la version anglaise.

docs(fr): spelling / orthographe

---

content/en/docs/4.directory-structure/10.plugins.md

For me as a Nuxt newbie the original sentence has been confusing and I thougth it was in a conflict with previous chapters.

docs: clarify what 'this function' means in memory leak warning

---

content/en/docs/6.internals-glossary/4.internals-nuxt.md

Fix a missing `this` in the example

docs: fix missing `this`

---

content/en/examples/8.middlewares/2.named.md

This pull request addresses the typo mentioned in [#2041](https://github.com/nuxt/nuxtjs.org/issues/2041).
The typo is fixed, issue [#2041](https://github.com/nuxt/nuxtjs.org/issues/2041) should be closed upon merge.

Fix typo (#2041)

---

content/en/docs/5.configuration-glossary/2.configuration-build.md

Revert accidental translation of an English markdown

fix(docs): revert EN `2.configuration-build.md`

---

content/en/docs/3.features/3.file-system-routing.md

The vue-router landing page is going to 404.

docs: Update Vue-router landing page link

---

content/en/docs/7.components-glossary/1.fetch.md

Fixing typo on 1.fetch.md

---

content/en/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md
content/es/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md
content/fr/tutorials/5.moving-from-nuxtjs-dotenv-to-runtime-config.md
content/ja/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md
content/pt-br/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md
content/pt/tutorials/4.moving-from-nuxtjs-dotenv-to-runtime-config.md

The _v_ should be _vs_, right?

docs: fix vs typo

---

README.md

Fixes the link of content folder

chore(readme): fix content link

---

components/organisms/home/HomeHero.vue

Fixes `Announcement` typo and Link responsiveness

fix(homepage): Nuxt 3 RC announcement typo & responsive

---

content/en/docs/4.directory-structure/8.modules.md

docs: remove deprecated webpack plugin syntax

---

content/en/docs/5.configuration-glossary/2.configuration-build.md
content/pt/docs/7.components-glossary/1.fetch.md
content/pt/docs/7.components-glossary/10.watchquery.md
content/pt/docs/7.components-glossary/2.head.md
content/pt/docs/7.components-glossary/3.key.md
content/pt/docs/7.components-glossary/4.layout.md
content/pt/docs/7.components-glossary/5.loading.md
content/pt/docs/7.components-glossary/6.middleware.md
content/pt/docs/7.components-glossary/7.transition.md
content/pt/docs/7.components-glossary/8.scrolltotop.md
content/pt/docs/7.components-glossary/9.validate.md
content/pt/docs/7.components-glossary/index.md

We are almost there, to complete the translation.
In this commit as usual I am sending a small package of
changes to facilitate the review process for all.
I am confident about the quality of this package, and take
in consideration of the number of files, this should be quick.
@smarroufin and @ChristopheCVB, it is your turn.

docs(pt): add components-glossary section translated

---

content/en/deployments/google-appengine.md

What was there previously gave 404 errors for all JavaScript files. I also updated the node version. 10 is outdated.

This is what worked for me

---

content/en/index.md
content/es/index.md
content/fr/index.md
content/ja/index.md
content/pt-br/index.md
content/pt/index.md

On the home page, the Hero primary buttons currently shows "39K+". I updated it to "40K+" for all locales.

docs: update GitHub stars count

---

content/en/deployments/pm2.md

docs: fix typo in pm2 guide

---

README.md

chore(readme): fix MDC VSCode extension link

---

content/en/docs/5.configuration-glossary/28.configuration-servermiddleware.md

Corrected a few typos and added a description of the client-server api pattern in Nuxt 2.

docs: add more explanation to server middleware section

---

content/en/docs/5.configuration-glossary/23.configuration-render.md

**Will need to wait until release of 2.16**
context: https://github.com/nuxt/nuxt.js/pull/9365

docs: update `render.static` false option

---

components/organisms/home/HomeHero.vue

fix: update link to new website

---

content/en/docs/1.get-started/1.installation.md

Nodejs (version >= v18.0.0) is not supported!
See: https://github.com/nuxt/nuxt/issues/10844

docs: recommend either node 16.x or 14.x

---

content/en/docs/5.configuration-glossary/23.configuration-render.md

Information taken from https://github.com/nuxt/nuxt.js/pull/3559 by @manniL

Document the option `render.csp.reportOnly`

---

content/en/docs/5.configuration-glossary/23.configuration-render.md

Link for open issue: https://github.com/nuxt/nuxt/issues/18376

docs: manual for shouldPreload and shouldPrefetch

---

content/en/docs/7.components-glossary/1.fetch.md

fixes https://github.com/nuxt/nuxt/issues/18811

docs: warn about setting `inheritAttrs: false` with fetch

---

content/en/deployments/kinsta.md

This PR updates the documentation about deploying to Kinsta:
- Restructure the document
- Add Static Site Hosting

[Docs] Adds Kinsta Static Site Hosting

---

content/ja/docs/1.get-started/1.installation.md

Fixed typo で → て

---

content/pt/index.md
i18n/pt-PT.js

Since I now have carte blanche to update the content of the Portuguese translation, I will send requests for updates larger than this one with several Markdown files changed.
If you're reading this description, and you're informed about the completion of the Portuguese content, then you may know that you can combine these changes without the reviewer's approval.
I'm their main author, as I'm also the main author of various Portuguese translations of Vue ecosystem tools, such as [pt.vuejs.org](https://pt.vuejs.org) and [pt.vitejs.dev](https://pt.vitejs.dev).

docs(pt): update content inside `pt/index.md` and `i18n/pt-PT.js`

---

content/pt/docs/2.concepts/1.views.md
content/pt/docs/2.concepts/2.context-helpers.md
content/pt/docs/2.concepts/3.server-side-rendering.md
content/pt/docs/2.concepts/4.static-site-generation.md
content/pt/docs/2.concepts/5.nuxt-lifecycle.md

Hi, colleagues!
I am back with one more huge update to bring to the Portuguese documentation of Nuxt 2.
I hope this pull request finds you well, and it is merged quickly. This way I could be able to go forward without delays.

docs(pt): update content inside `docs/concepts` folder

---

content/pt/docs/3.features/1.rendering-modes.md
content/pt/docs/3.features/10.transitions.md
content/pt/docs/3.features/11.live-preview.md
content/pt/docs/3.features/2.deployment-targets.md
content/pt/docs/3.features/3.file-system-routing.md
content/pt/docs/3.features/4.data-fetching.md
content/pt/docs/3.features/5.meta-tags-seo.md
content/pt/docs/3.features/6.configuration.md
content/pt/docs/3.features/7.loading.md
content/pt/docs/3.features/8.nuxt-components.md
content/pt/docs/3.features/9.component-discovery.md

In this pull request, I am sending a big update to the Portuguese content inside `features` folder.
I found some misspelling errors in the original content in the process that'll be corrected soon when I finish the updates.

docs(pt): update the translated content inside `features` folder

---

content/pt/lts.md

It was already time to translate the statement for end of life of Nux 2, so here is.

docs(pt): translate `lts.md` statement

---

content/pt/deployments/index.md
content/pt/events/index.md
content/pt/examples/1.routing/1.hello-world.md
content/pt/examples/1.routing/2.active-link-classes.md
content/pt/examples/1.routing/3.dynamic-pages.md
content/pt/examples/1.routing/4.nested-pages.md
content/pt/releases/index.md
content/pt/support/index.md
content/pt/teams/index.md
content/pt/testimonials/index.md
content/pt/tutorials/index.md
content/pt/video-courses/index.md
i18n/pt-PT.js

In this pull request, I am sending more updates to the various `index.md` files and I also updated the content inside `examples/routing` folder. I am almost there to finish the updates that will refine the understanding of the content.
Another notorious update was in the `i18n/pt-PT.js` file.
Thank you for your support in this endeavour, which may seem pointless or a waste of time to some.

docs(pt): update some `index.md` files and `examples/routing` folder

---

content/pt/docs/3.features/4.data-fetching.md
content/pt/docs/7.components-glossary/1.fetch.md
content/pt/docs/7.components-glossary/10.watchquery.md
content/pt/docs/7.components-glossary/2.head.md
content/pt/docs/7.components-glossary/3.key.md
content/pt/docs/7.components-glossary/4.layout.md
content/pt/docs/7.components-glossary/5.loading.md
content/pt/docs/7.components-glossary/6.middleware.md
content/pt/docs/7.components-glossary/7.transition.md
content/pt/docs/7.components-glossary/8.scrolltotop.md
content/pt/docs/7.components-glossary/9.validate.md
content/pt/docs/7.components-glossary/index.md

No comments this time, at least until I finish all.

docs(pt): update the content inside `components-glossary` folder
